### ISSUE TITLE
Signing functions based on authorship

### ISSUE THREAD

**Issue by davestanley** [DynaSim/DynaSim#100]
Since there are now several of us all developing DynaSim from scratch, I suggest that we embed authorship information in the comments section at the start of each function.

If the functions are missing documentation, needing revision, etc., this can be a good way of knowing who to contact (since it will not always be Jason).

I think we can do this informally for now - for example, here is how this was very informally done in GENESIS.

(Alternatively, we can just trace function history back using git log. But direct signing will be more robust, though old school.)

Object Type:    synchan
Description:    Synaptically activated channel. 
Author:         Mike Vanier 11/94
 

** Implemented by Eric De Schutter - January 1991
** Converted to NEUROKIT format by Upinder S. Bhalla. Feb 1991
** This file depends on functions and constants defined in defaults.g
*/

**Comment by davestanley** [comment]
@asoplata @jsherfey @kupiqu @erik-roberts @benpolletta 
I'm closing this issue, but wanted to tag you guys before doing so. I guess this is not so relevant since we have the blame function. But still it can be useful to see the original author in some cases

**Comment by jsherfey** [comment]
I added Author and Copyright to the functions I created. I think Dave has
done the same. There are only a few without Author info.

Erik and anyone else who has created functions, you can look at any of the
core functions or one of the MDD functions for examples of what to add to
yours.
