### ISSUE TITLE
Fixing path issues

### ISSUE THREAD

**Issue by davestanley** [DynaSim/DynaSim#103]
There are still some issues with treatment of paths, both addpath and also definition of the output path and studydir. 

I have fixed these in demos_xPlt.m, but it could still be replicated elsewhere. First, I removed all calls to change directory (cd). Second, I added a call to pwd in defining DynaSim path

`dynasim_path = fullfile(pwd,'..');`

Thus, paths are now absolute rather than relative (this was an issue in older versions of MATLAB).

See commits:
6b8fdb9210f7bf02118549dca3385cba52705b8c
d572d7047f483923d4ef56aef3a6dcc710fe0935

This is following up on the following 2 issues:
#97 
#94

**Comment by davestanley** [comment]
It would be good to update the demo scripts should be updated to use a similar format

**Comment by davestanley** [comment]
Just to clarify, adding the `pwd ` in there forces MATLAB to use absolute paths

**Comment by erikthered12** [comment]
some overlap with #32

**Comment by davestanley** [comment]
In some of my other code, I dealt with path issues by creating a file that defined the absolute path locations for all of my code:

https://github.com/cogrhythms/ds_kb3/blob/dev/my_paths.m

I then wrote the following function to query that path
https://github.com/cogrhythms/ds_kb3/blob/dev/funcs_general/funcs_queries/getpath.m
```
function out = getpath(query)
% out = getpath(query)
% Returns the value of the path variable specificed in query

    my_paths
    eval(['out = ' query ';']);
    
end
```

For example, running the command `path_roydata_orig` would return the string

`~/Miller/roy/CRC_Miller_data`

This might be useful if you want to allow user customization of where things are stored and to see these locations at a glance by looking at a single file.

Dave
