### ISSUE TITLE
Line 216 in demos_xPlt on branch master throws an error in Matlab R2013a. Version specific?

### ISSUE THREAD

**Issue by benpolletta** [DynaSim/DynaSim#105]
Error:

Warning: Struct field assignment overwrites a value with class "double". See
MATLAB R14SP2 Release Notes, Assigning Nonstructure Variables As Structures
Displays Warning, for details. 
> In subplot_grid>subplot_grid.figplace at 2447
  In xp_subplot_grid3D at 82
  In xPlt.recursivePlot at 89 
Error using set
Conversion to double from struct is not possible.
Error in subplot_grid/figplace (line 2449)
      set(this.hfig,'Units',prevunits);
Error in xp_subplot_grid3D (line 82)
            hsg(i).figplace(N1,i);
Error in xPlt/recursivePlot (line 89)
        [varargout{1:nargout}] =
        function_handles{1}(xp2,function_handle_arguments{1}{:});

**Comment by benpolletta** [comment]
Also some nasty stuff on line 225. Not sure, are these version specific?

Error using inputcheck>LocalCheckOption (line 343)
Illegal option '-RGBImage' given.
Error in inputcheck (line 86)
                opIndex = LocalCheckOption( cur_arg, options );
Error in print (line 166)
    [pj, devices, options ] = inputcheck( pj, inputargs{:} );
Error in xp_subplot_grid3D (line 64)
                cdata = print(h,'-RGBImage');
Error in xPlt/recursivePlot (line 89)
        [varargout{1:nargout}] =
        function_handles{1}(xp2,function_handle_arguments{1}{:});
Error in
xPlt/recursivePlot>@()recursivePlot(xp.subset(selection_curr{:}),function_handles(2:end),dimensions(2:end),function_handle_arguments(2:end))
(line 54)
                            xp2.data{i,j,k} = @()
                            recursivePlot(xp.subset(selection_curr{:}),function_handles(2:end),dimensions(2:end),function_handle_arguments(2:end));
                            Error in nDDict/subsref (line 632)
                [varargout{1:nargout}] = builtin('subsref',varargin{:});
Error in xp_subplot_grid3D (line 48)
                    xp.data{i,j}();
Error in xPlt/recursivePlot (line 89)
        [varargout{1:nargout}] =
        function_handles{1}(xp2,function_handle_arguments{1}{:});

**Comment by davestanley** [comment]
I ran the following segment of code (from the Master branch) on both my Mac laptop (2016b) and 2 different Matlab versions on the server (2013a and 2014b).

Looks like there are 2 issues here. Your first error is a problem with the figplace option in subplot_grid not being backwards compatible with MATLAB2013a. This a file from Mathworks central, so it might be possible to get an older version of it, or just comment out this line of code. (I'll add a catch in there for older Matlab versions)

The second issue you mentioned is also with the print RGBImage option also not being backwards compatible. This command is used when saving the plots as images. I'll put a warning in there against using it with older versions of MATLAB.
