### ISSUE TITLE
Mex Compilation Doesn't Support Varying of Mechanisms

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#106]
Makes 1 mex file for all sims.  That means the vary notation for switching out mechanisms won't work.  Temporary fix is to have all mechanisms at once, and vary conductance to 0 to switch in and out.  The covary mechanism helps with this, but is clunky.

**Comment by erikthered12** [comment]
Need to have dynasim check for varied mechs, and do a loop through the combinations of different mechs, and have mex compilation make separate m files.

**Comment by jsherfey** [comment]
This is what happens now. A new MEX file will be generated for every simulation of a model with mechanisms that have not been run before. It is not possible for a single MEX file to be used for models with different equations; therefore, the "temporary fix" suggested is the only approach that results in a single MEX file.

**Comment by erik-roberts** [comment]
fyi was added to the wiki q&a
