### ISSUE TITLE
Zip download doesn't have sub modules

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#112]
- need to have ds check for submodules (#129) 
- need to put separate zip file link in readme for downloading.
  - could write script that automatically makes zip with each push.

**Comment by erikthered12** [comment]
need to have ds check for submodules.

need to put separate zip file in readme for downloading.

**Comment by erik-roberts** [comment]
new master update scheme hard copies sub modules into master and hence zip now
