### ISSUE TITLE
Simulate DynaSim model using built-in Matlab solvers

### ISSUE THREAD

**Issue by jsherfey** [DynaSim/DynaSim#114]

**Comment by erikthered12** [comment]
#51

**Comment by jsherfey** [comment]
1. Use dynasim2odefun() to obtain required arguments for built-in solver; note: only ode23 and ode45 are compatible with compilation (i.e., when compile_flag is set to 1 in call to SimulateModel). 
2. Support odeset properties using SimulateModel and WriteMatlabSolver options (e.g., 'RelTol', 'AbsTol', 'InitialStep').
3. Implement WriteMatlabSolver() to create a m-file that specifies the model based on results from dynasim2odefun() and passes function handle to the built-in solver specified by the user. Note: could create an external m-file for the ODE system and pass a function handle to it instead of an anonymous function; that might result in faster integration.

**Comment by erikthered12** [comment]
current status:
ICS - need to figure out how to put ICs in params.mat for loading.  For local sim, would just have 1 sims worth.  For batch, would have values for all sims.

MEX - need to mex compile the separate odefun when not supported.

**Comment by davestanley** [comment]
Found an error in this branch. It seems that PrepareMEX contains references an options struct, which  was missing.

I have re-added it in   3253c79eee2178d9dbb53a1b956af1172d509117




PREPARING SOLVER:
Changing directory to /Users/davestanley/Dropbox/git/model-dnsim-kramer_IB/kramer_IB/solve
saving params.mat
Creating solver file: /Users/davestanley/Dropbox/git/model-dnsim-kramer_IB/kramer_IB/solve/solve_ode_20170313193300_077.m
Error: Undefined variable "options" or class "options.verbose_flag".
	 in PrepareMEX (line 32)
	 in GetSolveFile (line 173)
	 in SimulateModel (line 657)
	 in kramer_IB (line 566)
changing directory to /Users/davestanley/Dropbox/git/model-dnsim-kramer_IB/kramer_IB
Undefined variable "options" or class "options.verbose_flag".
Error in PrepareMEX (line 32)
  if options.verbose_flag
Error in GetSolveFile (line 173)
  solve_file = PrepareMEX(solve_file);
Error in SimulateModel (line 657)
          options.solve_file = GetSolveFile(model,studyinfo,options); % store name of solver file in options struct
Error in kramer_IB (line 566)
    data=SimulateModel(spec,'tspan',tspan,'dt',dt,'downsample_factor',dsfact,'solver',solver,'coder',0,...

**Comment by erik-roberts** [comment]
add in this to avoid out of memory issues with built in solvers:
https://www.mathworks.com/matlabcentral/fileexchange/31265-odesplit

**Comment by erik-roberts** [comment]
if it's interpolating anyway, why do downsample_factor after solve?

**Comment by erik-roberts** [comment]
Current status: Works locally.  Merged into dev.  Still issue with compilation on scc.

**Comment by davestanley** [comment]
What is the use case for Matlab solvers? Flexibility?

Dave

**Comment by kupiqu** [comment]
I thought they are faster, depending on how slowly a dynamic variable varies in time, but actually it makes sense that this apply to the accurateness as well when the variable varies extremely rapid, beyond the step size of a fixed step method.

See [https://www.mathworks.com/matlabcentral/answers/98293-is-there-a-fixed-step-ordinary-differential-equation-ode-solver-in-matlab-8-0-r2012b](https://www.mathworks.com/matlabcentral/answers/98293-is-there-a-fixed-step-ordinary-differential-equation-ode-solver-in-matlab-8-0-r2012b)

**Comment by kupiqu** [comment]
Also obviously, as these solvers are being used by thousands of people world-wide, they should be less prone to bugs

**Comment by benpolletta** [comment]
There is a kind of sensitive interplay between types of ODEs and types of
solvers which can solve them reliably and (numerically) stably. I've
noticed that some models don't exhibit the behavior I expect when I
simulate them with forward Euler, but do give the right behavior when you
simulate them with an RK4 method... I think the same is true of the
built-in solvers with adaptive time-step? I think stiff ODEs are relevant
to this conversation, too?

**Comment by jsherfey** [comment]
This was achieved with the completion of dsWriteMatlabSolver().
