### ISSUE TITLE
remove old git branches

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#121]
http://railsware.com/blog/2014/08/11/git-housekeeping-tutorial-clean-up-outdated-branches-in-local-and-remote-repositories/

**Comment by asoplata** [comment]
This counts as completed, right?

**Comment by erik-roberts** [comment]
there's a couple that probably still need to be removed.

**Comment by davestanley** [comment]
I ask that you leave the following:
`iss130_PlotData2`
`007_library_plots_updates`

as I am still working on these. I can change them to a different name if need be
