### ISSUE TITLE
MDD Submodule

### ISSUE THREAD

**Issue by davestanley** [DynaSim/DynaSim#123]
I moved the xPlt code into a submodule called MDD (MultiDimensional Dictionary). It's now accessible under DynaSim/MDD

https://github.com/davestanley/MDD

This means a few small changes to the workflow

- I moved the demos_xPlt.m script into this folder. As I update the xPlt code, I think it makes sense to have the changes to xPlt class locked to changes to the demos script so they will work well together.
- I'm eventually going to migrate the name nDDict over to the name MDD. I'm open to other naming suggestions, but was never really a fan of nDDict. 

More information on submodule creation and maintenance here
https://github.com/blog/2104-working-with-submodules
https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

To clone a new repo and include the submodule automatically, run the following modified clone command
`git clone --recursive git@github.com:DynaSim/DynaSim.git`

To update the submodule
`git submodule update --init --recursive`

If you don't do this, the MDD folder will appear EMPTY

**Comment by davestanley** [comment]
Working on fixing this
![image](https://cloud.githubusercontent.com/assets/5439305/23827497/1c2b8750-0683-11e7-936f-f9806cbe0a79.png)

**Comment by erikthered12** [comment]
yeah i moved it to dependencies

**Comment by erikthered12** [comment]
is this ready to be closed?

**Comment by erik-roberts** [comment]
I was able to clone without issue using:
git clone --recursive https://github.com/dynasim/dynasim.git
as in the install instructions

**Comment by erik-roberts** [comment]
switch to putting comments in:
https://github.com/davestanley/MDD/issues

unless they are related to MDD submodule. but for now submodule is working so issue is closed.
