### ISSUE TITLE
Submodule update fails

### ISSUE THREAD

**Issue by davestanley** [DynaSim/DynaSim#124]
stanleyd@scc2:temp$ git clone --recursive git@github.com:DynaSim/DynaSim.git
Initialized empty Git repository in /usr2/postdoc/stanleyd/src/temp/DynaSim/.git/
remote: Counting objects: 2586, done.
remote: Compressing objects: 100% (175/175), done.
remote: Total 2586 (delta 94), reused 0 (delta 0), pack-reused 2409
Receiving objects: 100% (2586/2586), 5.54 MiB, done.
Resolving deltas: 100% (1530/1530), done.
Submodule 'MDD' (https://github.com/davestanley/MDD) registered for path 'dependencies/MDD'
Initialized empty Git repository in /usr2/postdoc/stanleyd/src/temp/DynaSim/dependencies/MDD/.git/
error: Protocol https not supported or disabled in libcurl while accessing https://github.com/davestanley/MDD/info/refs

fatal: HTTP request failed
Clone of 'https://github.com/davestanley/MDD' into submodule path 'dependencies/MDD' failed
stanleyd@scc2:temp$ 
stanleyd@scc2:temp$

**Comment by davestanley** [comment]
Apparently this is an issues with libcurl. 

Switching back from using https version of reference to MDD

**Comment by erik-roberts** [comment]
i reverted this because of gitpage build error

**Comment by erik-roberts** [comment]
Here's my local output showing git clone working fine with HTTPS:

$ git clone --recursive https://github.com/dynasim/dynasim.git
Cloning into 'dynasim'...
remote: Counting objects: 2668, done.
remote: Compressing objects: 100% (257/257), done.
remote: Total 2668 (delta 140), reused 0 (delta 0), pack-reused 2409
Receiving objects: 100% (2668/2668), 5.57 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1576/1576), done.
Submodule 'MDD' (https://github.com/davestanley/MDD) registered for path 'dependencies/MDD'
Cloning into '/Users/erik/test/dynasim/dependencies/MDD'...
Submodule path 'dependencies/MDD': checked out '38a5d9d2b801e7d51d55606866cd42df8a7611aa'

**Comment by erik-roberts** [comment]
git clone --recursive isn't going to work on scc since it's older git version

**Comment by davestanley** [comment]
Awesome, glad this is working. The HTTPS page build error was annoying.

We should swap this command into the pull_all.sh bash script.

**Comment by erik-roberts** [comment]
I think there should be a separate one for the scc, or even better, have the bash script check the git version with a regexp and pick the appropriate command.
