### ISSUE TITLE
pull_all.sh check git version and change command

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#132]
have it do something like
git --version | grep -Eo '\d\.\d+\.\d+'
with check on numbers against (http://stackoverflow.com/questions/1030169/easy-way-pull-latest-of-all-submodules)

**Comment by erik-roberts** [comment]
How to update git on SCC to use modern submodule commands:
https://github.com/DynaSim/DynaSim/wiki/Developer-Q&A

**Comment by jsherfey** [comment]
pull_all.sh has been removed.
