### ISSUE TITLE
Check Submodule Dependencies

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#139]
Make a function that checks for existence of submodules.  Have any function with submodule dependencies call that function.

**Comment by benpolletta** [comment]
What's the use case for this? Are you thinking of this for other users,
i.e. as part of an installation check?

**Comment by erik-roberts** [comment]
if we do a file-specific check every time. otherwise could be just at installation.

**Comment by erik-roberts** [comment]
with new master not an issue
