### ISSUE TITLE
fileparts2 strangeness

### ISSUE THREAD

**Issue by davestanley** [DynaSim/DynaSim#141]
Fileparts2 is producing some unexpected behavior. Anyone else getting this?

Take some random string
```
>> study_dir
study_dir =
/Users/davestanley/Documents/DynaSimData/demos/demo_sPING_100cells_3x3
>> 
```

**fileparts vs fileparts2**
```
>> fileparts(study_dir)
ans =
/Users/davestanley/Documents/DynaSimData/demos
>> fileparts2(study_dir)
ans =
/Users/davestanley/Documents/DynaSimData/demos/demo_sPING_100cells_3x3
>> 
>> 
```

**fileparts vs fileparts2 with output**
```
>> [a,b,c] = fileparts(study_dir)
a =
/Users/davestanley/Documents/DynaSimData/demos
b =
demo_sPING_100cells_3x3
c =
  0×0 empty char array
>> [a,b,c] = fileparts2(study_dir)
a =
/Users/davestanley/Documents/DynaSimData/demos/demo_sPING_100cells_3x3
b =
  1×0 empty char array
c =
  0×0 empty char array
>> 
```

I tried replacing the original output with 

`[varargout{1:nargout}] = fileparts(file);`

which did not work

**Comment by erik-roberts** [comment]
fileparts2 is intended not to trim the trailing directory, regardless of whether there is a trailing slash or not.  fileparts will trim it if there is not a trailing slash but will trim it if there is a trailing slash.  That behavior is kind of erratic, so IMO it's best to use fileparts2 and add .. to go back a directory.

**Comment by davestanley** [comment]
Gotcha. I'm not a fan of using the '..' for aesthetic reasons, but still I'd prefer functionality over beauty so we can use this as a last resort.

For the cases where we need the parent directory, our options are :
`parentdir = cd(cd('..'))`

`parentdir = fileparts(pwd)`

`fullfile(fileparts2(pwd), '..')`

Apparently the second option has issues with paths containing a '.' (https://www.mathworks.com/matlabcentral/newsreader/view_thread/91777)

So perhaps we can use the 1st option, then?

**Comment by erik-roberts** [comment]
that's clever, didn't know that worked.
