### ISSUE TITLE
Set up unit testing as a submodule.

### ISSUE THREAD

**Issue by benpolletta** [DynaSim/DynaSim#145]
Have stable branch set to first (empty) commit, so users don't get access.

**Comment by erik-roberts** [comment]
issues:
  1)  dbstack uses the function name without the package.  this is workable when using a single package, but inwieldy with multiple packages or sub packages.
  2) have to call every function as ds.function, so lots of code had to be changed. might be nice to use a ds class so one doesn't have to do that.

implementing a ds class would avoid these issues.

**Comment by erik-roberts** [comment]
did we still want to do this?

**Comment by asoplata** [comment]
This was done as of commit 3b57fda.
