### ISSUE TITLE
behavior when options.study_dir unspecified

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#152]
When study_dir is not specified, setupStudy make a new folder in pwd when save_data_flag, save_results_flag, or parallel_flag is 1, but otherwise uses pwd itself.  It seems like it should be consistent regardless, perhaps unless compile mode is used, since that takes time.

**Comment by erik-roberts** [comment]
perhaps have save_solve_flag that determines if folder deleted

**Comment by erik-roberts** [comment]
consider hashing the model and varargin.

**Comment by jsherfey** [comment]
I think this has been resolved.

**Comment by erik-roberts** [comment]
what does it do now?
