### ISSUE TITLE
confirm options.overwrite_flag works

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#153]
options.overwrite_flag doesn't seem to overwrite fully.

**Comment by jsherfey** [comment]
It overwrites simulated data, analysis results, and saved plots.

**Comment by erik-roberts** [comment]
@jsherfey is it documented somewhere exactly what it overwrites? I was always confused about this.

`dsTutorial` just says "%     'overwrite_flag': whether to overwrite existing data files {0 or 1} (default: 0)"
