### ISSUE TITLE
dsAnalyze & array data

### ISSUE THREAD

**Issue by benpolletta** [DynaSim/DynaSim#163]
As it stands, dsAnalyze doesn't work the way AnalyzeStudy used to - assuming data is a vector of structures, and then applying a function handle to each element of data. Thus, even if data is a vector, if your analysis function operates on a scalar data object, you get a scalar data object out of dsAnalyze (the result of applying the function to the first element of data). This makes it hard to implement parallel execution (as in https://github.com/DynaSim/DynaSim/issues/162).

I would just change dsAnalyze to operate on vector data structures, but there seems to be some functionality built in for dsAnalyze to produce figures, and output figure handles. I don't know why this functionality would be baked into dsAnalyze and not dsPlot, but I'm hesitant to break it by merging in the fix I need. So, I need input here.

**Comment by erik-roberts** [comment]
dsAnalyze is the former AnalyzeResults.  ds.analyzeStudy is still there.  AFAIK, dsAnalyze only works on a single data structure, while ds.analyzeStudy was meant to work on an array of structs. I have almost finished merging the functionality on the branch for #98.

**Comment by erik-roberts** [comment]
@benpolletta, are you sure that there is now a missing functionality, and not just functionality that had never been implemented?

**Comment by benpolletta** [comment]
ae34c79f1ab2d27518cb06f8470ebc0ed9ea4785
