### ISSUE TITLE
make a checkDependencies function

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#169]
have a function that checks all the matlab dependencies and makes sure that they are on path/exist

**Comment by erik-roberts** [comment]
https://www.mathworks.com/help/matlab/matlab_prog/identify-dependencies.html

**Comment by jsherfey** [comment]
Dependencies are checked as needed. Options that require missing dependencies are automatically turned off and a warning message is displayed.

**Comment by erik-roberts** [comment]
> Dependencies are checked as needed. Options that require missing dependencies are automatically turned off and a warning message is displayed.

how are they checked?
