### ISSUE TITLE
Standardize in-code function documentation

### ISSUE THREAD

**Issue by asoplata** [DynaSim/DynaSim#17]
Currently, the long comments after function definitions are of a custom style. A standardized style of describing all the important properties of a function, e.g. one compatible with [Doxygen](http://www.stack.nl/~dimitri/doxygen/) etc., will make it trivial to generate documentation compatible for upload to [readthedocs](https://readthedocs.org/).

Therefore, we should
1. decide on a standard for documentation, preferably one that's easily machine-readable by some library
2. convert all the documentation into that standard.

**Comment by asoplata** [comment]
Pursuant to #18, barring major complaints about [Sphinx](http://www.sphinx-doc.org/en/stable/) in the future, I'm planning on switching all the documentation (in the form of long "docstrings" immediately after the function declarations) over to the Sphinx style.

**Comment by asoplata** [comment]
In my research for #18, it's become apparent to me that there is no good officially-recommended way to fully document a MATLAB function, as recommended by the MathWorks people. This means how we choose to standardize our documentation is completely up to us.

**Comment by asoplata** [comment]
There is very, very little functionality possible in the MATLAB function documentation comment immediately after the function definition, either for native MATLAB or via M2HTML. The only "features" are that:

1. The first line of the documentation comment is considered the "synopsis" and should have both the function name and a single-line, brief description of what the function does (and that doesn't use the same verb as in the function!)
2. After that, it's generally a good idea to have Description, Inputs, Outputs, Examples, Notes, and See Also sections in the single comment block. I have tried to reorganize the documentation for these sections in a pseudo-Markdown style
3. If you mention other functions after See Also, both MATLAB and M2HTML will show hyperlinks to those functions in the help/HTML interfaces.

I've redone the core code documentation, and due to the lack of features in the documentation, I'm closing this, since our standard is mostly "keep it simple and clean".

**Comment by erik-roberts** [comment]
@asoplata would you mind adding the basic template here:
https://github.com/DynaSim/DynaSim/wiki/Documentation-Template
