### ISSUE TITLE
Fix errors associated with renaming xPlt and nDDict to MDict

### ISSUE THREAD

**Issue by davestanley** [DynaSim/DynaSim#173]
These changes to MDD are going to create a lot of errors in DynaSim. Renaming things now.

**Comment by davestanley** [comment]
Done

**Comment by davestanley** [comment]
Reopened this because we're now changing the name back to MDD!

**Comment by erik-roberts** [comment]
is this done @davestanley ?

**Comment by davestanley** [comment]
Yep, all done.
