### ISSUE TITLE
checkCovary returns an index of zero in linked_inds

### ISSUE THREAD

**Issue by davestanley** [DynaSim/DynaSim#180]
This produces an error when trying to index linked columns (since 0 is not a valid index). Not sure yet if this is a bug or an intentional feature of checkCovary; if it is a feature it would be helpful to have some documentation of checkCovary to know when a zero might be returned.

See also #175. This can in certain circumstances generate errors when running dsPlot2, which now relies on checkCovary (this will likely affect dsPlot as well, although I haven't yet found a specific example of this).

**Comment by davestanley** [comment]
@benpolletta , can you have a look?

**Comment by benpolletta** [comment]
It uses zero because the first index isn't supposed to be marked for
removal, and we want all indices marked for removal in this case... Can you
send an example where you run into problems with this code?

**Comment by davestanley** [comment]
@benpolletta , the code that was producing looked something like this:

vary_labels = data(1).varied; % data(1).simulator_options.vary;

for i =1:length(linked_inds)
     vary_labels(linked_inds{i})
end

It throws an error due to linked_inds{i) sometimes equaling zero. 

However, I'm actually no longer using this function (wrote my own solution for checking for covaried parameters, see iss #183). I'm using this new function in dsPlot2

**Comment by benpolletta** [comment]
Welp, glad I spent all that time writing that stupid thing, then.

**Comment by davestanley** [comment]
I actually spent a good amount of time figuring out how your code works and seeing ways to modifying it to produce the outputs I needed. It ended up being easier to start from scratch, since our approaches are so different.

However, I did use the linear algebra solution you suggested (for part 1) and also am re-using the nchoosek sections of your code for part 2 in #183 .
