### ISSUE TITLE
Compiler dependency not working on 2017a

### ISSUE THREAD

**Issue by asoplata** [DynaSim/DynaSim#184]
@benpolletta reported (see #181 ) that cluster submission with compiled (?) jobs seems to fail due to a ZLIB linked library error:

    PREPARING BATCH:
    created temporary lock file for this process: /projectnb/crc-nak/brpp/model-dnsim-kramer_IB/kramer_IB/kramer_IB_15_40_2.488/.lock_20170608154040071_0
    saving study file: /projectnb/crc-nak/brpp/model-dnsim-kramer_IB/kramer_IB/kramer_IB_15_40_2.488/studyinfo.mat
    deleting temporary lock file for this process: /projectnb/crc-nak/brpp/model-dnsim-kramer_IB/kramer_IB/kramer_IB_15_40_2.488/.lock_20170608154040071_0
    Submitting cluster jobs with shell command: "echo '/projectnb/crc-nak/brpp/DynaSim/functions/+ds/qmatjob_array_one_file /usr2/postdoc/brpp/batchdirs sim_job' | qsub -V -hard -l 'h_vmem=8G' -wd /usr2/postdoc/brpp/batchdirs -N batchdirs_sim_job -t 1-41:1"
    Submit command failed: "echo '/projectnb/crc-nak/brpp/DynaSim/functions/+ds/qmatjob_array_one_file /usr2/postdoc/brpp/batchdirs sim_job' | qsub -V -hard -l 'h_vmem=8G' -wd /usr2/postdoc/brpp/batchdirs -N batchdirs_sim_job -t 1-41:1"
    qsub: /lib64/libz.so.1: version `ZLIB_1.2.3.3' not found (required by /share/pkg/matlab/2017a/install/bin/glnxa64/libxml2.so.2)

This could be an issue with the MATLAB install itself on the cluster, or how MEX compilation is linking confusingly-named ZLIB library objects: https://www.mathworks.com/matlabcentral/newsreader/view_thread/140611

**Comment by erik-roberts** [comment]
#181

**Comment by jsherfey** [comment]
The compiler works in 2017a now.

**Comment by erik-roberts** [comment]
in the future, as salva pointing out somewhere, one can use module to load a newer zlib version if this sort of thing happens again.
