### ISSUE TITLE
h_vmem vs mem_total in qsub options

### ISSUE THREAD

**Issue by asoplata** [DynaSim/DynaSim#193]
Our `qmatjobs_memlimit_loop`, which is used in submitting cluster jobs, uses an option called `h_vmem` to set the memory limit. This has so far worked for the life of the program, I believe. However, this option is [COMPLETELY unmentioned by the BU SCC documentation](http://www.bu.edu/tech/search/?q=h_vmem), and they say to [use `mem_total` instead](http://www.bu.edu/tech/support/research/system-usage/running-jobs/submitting-jobs/). Since I'm doing benchmarking, I'm curious about this - why are we using an unmentioned option for this, and does it differ at all from using `mem_total`?

I realize that the reason is probably that Jason used `h_vmem` on the last cluster he used (before BU), but I'm having a hard time finding exact information online about what the difference is, if any.

*edit: wrong markdown formatting, and wrong search string in URL. Results are the same, though.

**Comment by asoplata** [comment]
So, interestingly, I've been playing with trying to run some benchmarks only on the same nodes/hardware ([complete list here](http://www.bu.edu/tech/support/research/computing-resources/tech-summary/)). I noticed something interesting: when I use `h_vmem` and hard-code in my memory request to be 252G ([see commit here](https://github.com/DynaSim/DynaSim/commit/9e4895bf741a9ddbfd3f64bdf3f81d4728c09fd1)), I found that the cluster gave me node `scc-mb2`, which correctly has 16 cores, sandybridge architecture...**but only 128GB of memory, HALF of what I requested**!

I'm testing using `mem_total` instead of `h_vmem` right now, which is taking a lot longer to queue (which is good), but it's _possible_ that our use of `h_vmem` has meant we're not getting the minimum physical memory we've been requesting. Judging from the name, we may be getting our requested memory via virtual memory, but TBH I don't understand the difference between real and virtual memory and thus cannot comment on how that would effect our speed or anything else.

**Comment by asoplata** [comment]
Update: using `mem_total` seems _more likely_ to use a node with real, physical memory of at least what's requested (based on a very small sample), but I **still** get jobs run with `mem_total` on nodes with only 128G of memory. It seems that either way, the cluster seems to think it's okay to use virtual memory in place of physical memory for some/many (?) of our simulations. As far as I can tell from the [documentation](http://www.bu.edu/tech/support/research/system-usage/running-jobs/submitting-jobs/) there is no way to DEMAND a minimum of physical memory, other than (as Ben suggested) specifically asking for a specific node that you already know has the hardware you want. I'll try this next.

**Comment by asoplata** [comment]
Update: Sigh. After talking with IT and using Dave's idea to ssh into individual nodes and inspect how much memory they report, it seems today has been plagued by 2 bugs: 

1. [the Tech Summary page](http://www.bu.edu/tech/support/research/computing-resources/tech-summary/) of hardware specs for the SCC cluster is not up to date with what ACTUAL hardware is available on the nodes (e.g. `scc-cb5` reports 256GB of memory via top, but on the webpage is indicated as having 128GB)
2. Using the ssh/top method to individually examine nodes, it seems `h_vmem` DOES send our requested-252GB nodes to real, physical 128GB nodes (e.g. `scc-pg2`), but so far I have NOT seen `mem_total` do this. I'm going to do more testing to see if `mem_total` ever gives me a 128GB node when I'm requesting 252GB.

**Comment by asoplata** [comment]
Update: After taking a sample of about 25 simulations using `mem_total`, I have yet to find ANY simulation that did not use a true minimum 252GB node. Using `h_vmem` uses a 252GB node most of the time, but not always - sometimes the `h_vmem` simulations uses 128GB nodes.

Therefore, unless someone can find a counterexample, **we should probably switch to using `mem_total` instead of `h_vmem`** to make sure we're getting the memory we're requesting, since `h_vmem` does NOT give us the physical memory we're requesting.

My guess is `h_vmem` is giving us the virtual memory we're requesting, but since virtual (on-disk) memory can be MUCH slower than physical (RAM) memory, I think we should not use it at all.

**Comment by jsherfey** [comment]
@kupiqu: can you change h_vmem to mem_total in qmatjobs_memlimit_loop when you edit it for Octave compatibility?

**Comment by kupiqu** [comment]
Sure
