### ISSUE TITLE
Synapse Syntax Unclear

### ISSUE THREAD

**Issue by benpolletta** [DynaSim/DynaSim#199]
I have been under the assumption that pop1->pop2 specifies a synapse from pop1 onto pop2. Currently, I am varying g_SYN for pop1->pop2, using that syntax, on debug. However, the simulations show without a doubt that what has been varied is pop2->pop1. Which one of these is the correct syntax - pre->post or (the counterintuitive and highly error prone) post->pre? Is this a bug in one model where there are synapses using the same mechanism in both directions? Is this a bug induced by a recent commit? Will I ever get the simulation I am trying to run working the way I want it to (I am on my third baffling bug/ugly hack)? Stay tuned...

**Comment by jsherfey** [comment]
Hey Ben,

Can you share the current version of your model. I'll try to debug it
tonight. I'm not sure if the problem is related to recent commits or
something in the model. The correct syntax is pre->post; post<-pre also
works.

**Comment by jsherfey** [comment]
There is an example varing tauDx for I->E in dsDemos. Does that set of sims
work correct for you?

**Comment by benpolletta** [comment]
Hi Jason (et al.),

So, the problem doesn't seem to occur in dsDemos. It seems to be a problem
going from the vary statement to the parameter structure p for cluster
jobs, since the synapse parameters are correctly labeled in the "base
model", and only the varied conductances need to have the labels reversed,
and already have the labels reversed in the structure p. Do you have any
idea where the vary statement is converted to the parameter structure p for
cluster jobs?

B

**Comment by jsherfey** [comment]
pre->post and post<-pre are both supported correctly now.
