### ISSUE TITLE
Delineate user-specific data/functionality from DynaSim-provided stuff

### ISSUE THREAD

**Issue by asoplata** [DynaSim/DynaSim#20]
One thing we haven't worked through is to clear the separation between what is considered part of the canonical repo vs. what do individual users do with private, individual-user specific code like custom private mechanisms or analysis code. You can't have two different git repos in the same directory IIRC, but we do want to provide a DynaSim install with some starter cell mechanisms, etc...but we also want to make it easy for people to share them without having to worry about conflicts/etc. with the DynaSim GitHub repo. How we manage this will probably impact our choice of Git development.

A good use-case is, say I've made the mechanism files for a model, and put it in a GitHub repo like a good little researcher. Now, someone else in the lab wants to just clone those mechanisms and start simulating with them immediately -- what does that person do? if they `git clone` inside their `dynasim/mechanism` subfolder, now you've confounded two git repos that very well may interfere with each other. If there's no functional problem with what I just described (just downloading subfolders of mechanisms directly into the `mechanisms` folder), then okay great.

My main point is, **NO paths should be hardcoded**, similar to how `~/research/modeling/database` was in the former DNSIM. Maybe this isn't a problem at the moment, but we need to be vigilant in requiring that everyone's install works the same way -- the simplest way being, "se,t these three environment variables in your ~/.bashrc to wherever you have your stuff stored".

**Comment by asoplata** [comment]
A big part of my thinking for this issue is the installation process: we should try to limit forcing the user to set bash environment variables, and MATLAB paths (permanently), and temporary MATLAB paths, all in different places or different ways. We should pick one and stick to it.

Bash/general environment variables are the most feature-rich, but AFAIK they're kind of a pain to set on Windows. **MATLAB paths**, I would hope, should be the most cross-platform solution. In the ideal case, one could add new groups of mechanisms by simply adding that directory to the MATLAB path.

- A sub-problem of using MATLAB paths for everything is ensuring that they're read by the MATLAB scripts for individual batch jobs, but this may already be working.
- This requires `LocateModelFiles` etc. to search the whole MATLAB path, which also means that duplicately-named/confounded mechanisms etc. will create conflict across the whole system, as they will be confused. I don't think this is very bad, though, as nonuniquely identifying similar mechanisms is a Hard problem anyways for us.
- Once the install is only set through MATLAB paths, then that means the code should run from anywhere, right?

**Comment by asoplata** [comment]
Sigh. As per #24 I'm now of the opinion that MATLAB's `pathdef` utilities for handling search paths for code don't work on the SCC cluster that many of us use. Thankfully, using `~/Documents/MATLAB/startup.m` like I describe successfully installs DynaSim globally.

Assuming we want to use `~/Documents/MATLAB/startup.m` as the default installation for DynaSim code in general, it stands to reason that maybe we can use the same way to install **alternative directories full of DynaSim mechanisms**. I can't remember if they have their own filetype like `.mech` or `.mdl`, but if they do, and we can search for those non-MATLAB filetypes along the MATLAB search path upon startup, then "installing" an independent folder of DynaSim mechanisms (e.g. that are their own, different, git repo) would be as simple as, like installing DynaSim, adding their location to `~/Documents/MATLAB/startup.m` and bam, you're done -- assuming that works for the cluster being able to locate mechanisms as well.

The latter thing may need its own full investigation -- do the individual cluster jobs read from `~/Documents/MATLAB/startup.m` too? Or a different startup file?

...after a commercial break...

YES! I threw in a `fprintf(fjob, 'which startup\n');` into `CreateBatch` and the stdout showed that the `startup` used was my personal one, a la `~/Documents/MATLAB/startup.m`! This is GREAT news for this installation method, as this means that batch jobs may be able to source their mechanism directories straight from the local user's `~/Documents/MATLAB/startup.m`! Hooray

**Comment by asoplata** [comment]
Models and mechanisms can be saved into an arbitrary order of subfolders inside the `models` folder. This is the simplest and probably best approach to coordinating local vs. built-in models and mechanisms: let the researcher handle it themselves, and in an intuitive way (just copying it into the `models` folder).

**Comment by erik-roberts** [comment]
part of this is already solved. we have a personal folder in mechanisms that is in git ignore. you clone into that.
