### ISSUE TITLE
change function naming convention for a final time?

### ISSUE THREAD

**Issue by jsherfey** [DynaSim/DynaSim#211]
After consulting with a number of users, most with a preference prefer lower case with underscores because of its greater readability over lower camel case. Clarity is probably a more important factor than minor differences in efficiency in this case.

For instance,

data = ds_simulate(eqns)

is more readable than

data = dsSimulate(eqns)

After experimenting with both, I agree. I also find pressing the Shift + _ keys to create a satisfying division between the part of the function name referencing the toolbox and the part referencing the unique function that is otherwise ambiguous with the current naming convention.

Does anyone disagree and think we should stick with lower camel case (i.e., as in the latest version)?

**Comment by jsherfey** [comment]
Let's leave it as is.

**Comment by erik-roberts** [comment]
i prefer lower camelcase, especially for fn names. it's easier to type and I think looks better.
