### ISSUE TITLE
Master currently broken, likely due to predefined mechanism usage

### ISSUE THREAD

**Issue by asoplata** [DynaSim/DynaSim#213]
I just tried the latest `master` branch in an interactive session on the cluster (2013a), and DynaSim fails when trying to use mechanisms from mechanism files like `iNa.mech`. I got an error on line 170 when running `dsDemos.m`: `"Undefined function 'mrdivide' for input arguments of type 'function_handle'"`, and when I just try running the below segment from `dsDemos.m`, I get a different error `"Reference to non-existent field 'mechanisms'"`. I think using pre-specified mechanisms is broken right now.

```{matlab}
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% BUILDING LARGE MODELS WITH MULTIPLE POPULATIONS AND CONNECTIONS
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Setup Sparse Pyramidal-Interneuron-Network-Gamma (sPING)

% define equations of cell model (same for E and I populations)
eqns={
  'dv/dt=Iapp+@current+noise*randn(1,N_pop)';
  'monitor iGABAa.functions, iAMPA.functions'
};
% Tip: monitor all functions of a mechanism using: monitor MECHANISM.functions

% create DynaSim specification structure
s=[];
s.populations(1).name='E';
s.populations(1).size=80;
s.populations(1).equations=eqns;
s.populations(1).mechanism_list={'iNa','iK'};
s.populations(1).parameters={'Iapp',5,'gNa',120,'gK',36,'noise',40};
s.populations(2).name='I';
s.populations(2).size=20;
s.populations(2).equations=eqns;
s.populations(2).mechanism_list={'iNa','iK'};
s.populations(2).parameters={'Iapp',0,'gNa',120,'gK',36,'noise',40};
s.connections(1).direction='I->E';
s.connections(1).mechanism_list={'iGABAa'};
s.connections(1).parameters={'tauD',10,'gSYN',.1,'netcon','ones(N_pre,N_post)'};
s.connections(2).direction='E->I';
s.connections(2).mechanism_list={'iAMPA'};
s.connections(2).parameters={'tauD',2,'gSYN',.1,'netcon',ones(80,20)};

%% Simulate Sparse Pyramidal-Interneuron-Network-Gamma (sPING)
data=dsSimulate(s, 'study_dir','demo_sPING_0');
```

**Comment by asoplata** [comment]
The test script works correctly up until commit 29c774d, after which I get the error I saw. So it's same to assume that the bug lies in the changes to `specifications.populations.equations`.

**Comment by asoplata** [comment]
This also means that `master` has not been able to use pre-defined mechanisms for roughly a month, and so the `dsDemos.m` script breaks very early.

**Comment by asoplata** [comment]
`dsGenerateModel.m` as of 29c774d fails at Line 351 in the IF condition when checking for if `MechID` is in `specification.connections(i).mechanisms.name`. However, when I debug the test script above, the only relevant subsubfield is `specification.connections().mechanism_list`. There is no subsubfield called `...mechanisms`, and no subsubsubfield called `...mechanisms.name`, so the check for if `MechID` is a member causes an error.

Looking through the rest of the codebase, support for `...mechanisms` instead of `...mechanism_list` seems to be a legacy thing. However, even in the legacy code, there is no use of `...mechanisms.name`, which seems to be entirely new to this commit. @jsherfey were you intending to write code that interpreted `...mechanisms.name` from `...mechanism_list`?

This code block seems to have been added rather than replacing pre-existing code. @jsherfey was this a commit in the middle of adding new `...mechanism`-type subfield support, judging from the commit title? It seems like only half the code is in here, since the code now RELIES on the existence of several subfields, but those subfields are not generated automatically even when using pre-defined mechanisms. It seems like there's missing code to this.

Until this is fixed, the most recent working version of `master` seems to be the commit before it, 7c02e9e

**Comment by erik-roberts** [comment]
from git blame:
`9dcfdc84 functions/internal/dsGenerateModel.m (Jason Sherfey 2017-07-02 04:49:31 -0400 351)     if ~isempty(specification.connections(i).mechanisms) && ismember(MechID,{specif
ication.connections(i).mechanisms.name})`

**Comment by erik-roberts** [comment]
remaining bug on line 170, related to `Cm=1` not getting added to params

**Comment by asoplata** [comment]
Okay, it seems that this issue is tied to BOTH 9dcfdc8 that was on `sherfey_updates` and 29c774d which is on `master`. If you run `git show` on these, you'll see these two commits are almost completely identical. It is unclear why this same commit was put on `master` completely separately from the rest of the `sherfey_updates` code. We will try to deal with this at the 3pm meeting today.

**Comment by jsherfey** [comment]
Master was fixed a few weeks ago.
