### ISSUE TITLE
Mexes path

### ISSUE THREAD

**Issue by davestanley** [DynaSim/DynaSim#216]
Necessary changes to mexpath mode for compiling:
- Make mexpath search default solve folder first
- Change mexpath default to be DynaSim documents folder
- Possibly create a flag to make mexpath mode optional

Requested by @jsherfey

**Comment by davestanley** [comment]
Finished these changes. Here is the summary:

Previously dsSimulate would drop compiled mex files in the folder ``./mexes`` (e.g. using a path relative to ``study_dir``). It would also search for them in the same location when re-running with compile_flag turned on.

Now, instead, ``mex_dir`` is by default in Documents folder (determined by dsConfig.txt - which in turn is determined by dsMakeDefaultConfig.m). This folder will form a common pool for mex files of all simulations. If it gets too large, it may need to be cleaned out.

Alternatively, users can disable this functionality by setting ``mex_dir_flag`` to 0. ``mex_dir_flag`` is set to 1 by default, but setting it to zero will force DynaSim to only search in the current solve folder for mexes and nowhere else.

**Comment by erik-roberts** [comment]
@jsherfey @davestanley why was this necessary? i don't think it's working.  also, how does it find the correct mex file? is there some hashing or something?
