### ISSUE TITLE
Cluster mode specify matlab version

### ISSUE THREAD

**Issue by davestanley** [DynaSim/DynaSim#218]
I am using Matlab 2017a for most of my simulations, which supports some compilation options that are not supported in MATLAB 2014 (currently the default for cluster mode)

Is there a way to change the default MATLAB that is loaded when running on the cluster?

**Comment by kupiqu** [comment]
https://github.com/DynaSim/DynaSim/issues/161#issuecomment-299205109

**Comment by davestanley** [comment]
@kupiqu 
Yes, I already loaded the module, and put
``module load matlab/2017a``
in my .bashrc

However, when I submit jobs to the cluster, it still loads MATLAB2014. I cannot seem to change this. I think we need to put an option within DynaSim that puts the module load command directly in the scripts sent to the cluster.

**Comment by kupiqu** [comment]
I call this bash script launch_matlab.sh:
```
#!/bin/bash -l
if [ "$#" -gt 1 ]; then
  echo -e "\nIllegal number of parameters, at most one, matlab version, e.g. 2014a\n"
else
  if [ "$#" -eq 1 ]; then
    matlabv="matlab/$1"
  else
    matlabv="matlab/2014a"
  fi
  cwd=$(pwd)
  cd /projectnb/crc-nak/sardid/
  msg=$( { module load $matlabv; } 2>&1 )
  if [[ $msg == *"ERROR"* ]]; then
    # save log for exception
    echo -e "\nUnknown matlab version, using default (2014a)\n"
    matlabv="matlab/2014a"
  fi
  echo -e "\nLoading $matlabv\n"
  module load $matlabv
  matlab -nodisplay -singleCompThread
  cd $cwd
fi
```

You can adapt it to your needs if you want

**Comment by kupiqu** [comment]
In matlab I do sth like this to create it on-the-fly (for the case it helps in porting it to DynaSim):

```
      % Single simulation

      launch_filename = [dirname,'/launch_',identifier];
      % m script
      fid = fopen([launch_filename,'.m'],'w+');

      % fprintf(fid,'rng(%d);\n',iter);
      fprintf(fid,'rng(''shuffle'');\n');

      fprintf(fid,'try\n');

      fprintf(fid,'  cd(''%s'');\n',cwd);
      fprintf(fid,'  cwd = pwd;\n');
      fprintf(fid,'  cluster_flag = %d;\n',cluster_flag);
      fprintf(fid,'  %% loading model specification\n');
      fprintf(fid,'  load(''%s'',''StrMicrocircuit_spec'');\n',specmat);

      fprintf(fid,'  addpath(pwd);\n');

      fprintf(fid,'  %% running simulation\n');
      fprintf(fid,'  data = runsim(StrMicrocircuit_spec,''timelimits'',[%g,%g],''dt'',%g,''SOLVER'',''%s'',''dsfact'',%d,''timesurfer_flag'',0,''verbose'',0,''coder'',%d,''debug'',%d,''cluster_flag'',%d,''identifier'',''%s'');\n',tspan(1),tspan(2),dt,solver,dsfact,coder_flag,debug_flag,cluster_flag,[dirname,'_',identifier]);

      fprintf(fid,'  rmpath(pwd);\n');

      fprintf(fid,'  %% saving data\n');
      fprintf(fid,'  flagExist = 1;\n');
      fprintf(fid,'  save(''%s'',''data'');\n',datamat);
      fprintf(fid,'  save(''%s'',''flagExist'',''-append'');\n',datamat);
      fprintf(fid,'  clear data;\n');
      if debug_flag == 0
        fprintf(fid,'  delete(''%s'');\n',[launch_filename,'.m']);
        if cluster_flag
          fprintf(fid,'  delete(''%s'');\n',[launch_filename,'.sh']);
        end
      end

      fprintf(fid,'catch ME\n');
      fprintf(fid,'  fprintf(''\\n\\nCatched ME error: %%s\\n\\n'',ME.message);\n');
      fprintf(fid,'  for i=1:length(ME.stack)\n');
      fprintf(fid,'    fprintf(''\\t in %%s (line %%g)\\n'',ME.stack(i).name,ME.stack(i).line);\n');
      fprintf(fid,'  end\n');
      fprintf(fid,'  if cluster_flag == 0\n');
      fprintf(fid,'    system(''notify-send ".m Script" "The simulation has been interrupted" -t 2 -i emblem-important.svg'');\n');
      fprintf(fid,'  end\n');

      fprintf(fid,'  cd(cwd);\n');
      fprintf(fid,'  return;\n');
      fprintf(fid,'end\n');
      fclose(fid);
      if cluster_flag == 0
        run(launch_filename);
      else
        % bash script
        fid = fopen([launch_filename,'.sh'],'w+');
        fprintf(fid,'#!/bin/bash -l\n');
        fprintf(fid,'cd /projectnb/crc-nak/sardid/\n');
        matlabv = version('-release');
        fprintf(fid,'module load matlab/''%s''\n',matlabv);
        fprintf(fid,'matlab -nodisplay -singleCompThread -r "cd %s;clear;run(''%s'');exit;";\n',cwd,launch_filename);
        fclose(fid);
        % job submission
        system(['qsub -l h_rt=00:30:00 -e ',[dirlogs,'/',identifier,'.err_jid$JOB_ID'],' -o ',[dirlogs,'/',identifier,'.out_jid$JOB_ID'],' -m a -m s ./',launch_filename,'.sh']);
      end
```

**Comment by davestanley** [comment]
Is there no way to specify which modules are loaded by default with new cluster jobs?

After putting these in my .bashrc, new terminal sessions start with Matlab2017 module already loaded.

**Comment by kupiqu** [comment]
That would be the best, but I'm not sure about that

**Comment by asoplata** [comment]
The Matlab version used on the cluster is currently hardcoded into `qmatjob_loop` here https://github.com/DynaSim/DynaSim/blob/master/functions/internal/qmatjob_loop#L13 . We should add yet another option to pass which version we want to use, like "2014a", that fails if that version is not found.

**Comment by jsherfey** [comment]
I changed the qmatjob_loop script to simply call "matlab" instead of a
hard-coded version. That way it will use whatever version "matlab" points
to.

I'm not sure who hard-coded 2014a, or what the rationale was, BUT, that
probably won't work when non-BU users try using cluster_flag on a different
cluster.

Can someone test the update on dev with a more recent version of Matlab and
make sure cluster jobs run successfully? If so, we should be able to close
this issue.

**Comment by kupiqu** [comment]
We probably should call repotUI to either call matlab or octave, shouldn't we? (the name is biased too, I guess mat refers to matlab, but that is a minor thing in comparison, I guess there are some little biases like that all around).

Currently DynaSim doesn't work in Octave in the cluster, but that's a matter of the available version (4.0.2 instead of 4.2.1). So for now, there is no way to test the cluster section of DynaSim in Octave. I will open a ticket to see if IT can install current stable version of Octave in the cluster.

**Comment by jsherfey** [comment]
That's a great idea. Once IT updates the cluster to Octave 4.2.1, let's add
a reportUI switch to dsCreateBatch (around lines 407-425) to submit jobs
using new Octave-specific shell scripts, qoctavejobs_memlimit_loop and
qoctavejob_loop.

**Comment by kupiqu** [comment]
Ticket is open already. I guess they will say sth about it this week...

**Comment by kupiqu** [comment]
This issue was specific about a bug wrt matlab, which is fixed. Closing...

I will open another more specific issue for Octave

**Comment by erik-roberts** [comment]
array mode still needs to be fixed.

**Comment by erik-roberts** [comment]
done
