### ISSUE TITLE
Bug when using underscore "_" within population name 

### ISSUE THREAD

**Issue by kupiqu** [DynaSim/DynaSim#219]
Population name is for instance D1_MSN, and the Npop field should read D1_MSN_Npop. However, the code instead tries to reach D1_Npop, which is not found:

```
Error: Reference to non-existent field 'D1_Npop'.
         in dsWriteDynaSimSolver (line 435)
         in dsGetSolveFile (line 151)
         in dsSimulate/tryFn (line 907)
         in dsSimulate (line 747)
```

Until this is fixed, it can be (obviously) workarounded by avoiding underscore characters in population names, e.g. D1MSN.

**Comment by jsherfey** [comment]
fixed in 1c3521d55989d1ece35bd82d69c692b7e8c105bb.
