### ISSUE TITLE
DynaSim error in Octave: using ismember upon an empty array

### ISSUE THREAD

**Issue by kupiqu** [DynaSim/DynaSim#220]
I'm checking the code in dsDemos in Matlab vs Octave. The first error I found is the following:

```
eqns={
  's=10; r=27; b=2.666'
  'dx/dt=s*(y-x)'
  'dy/dt=r*x-y-x*z'
  'dz/dt=-b*z+x*y'
};

data=dsSimulate(eqns, 'tspan',[0 100], 'ic',[1 2 .5], 'solver','rk4','study_dir','demo_lorenz');

error: Invalid call to lookup.  Correct usage is:

 -- IDX = lookup (TABLE, Y)
 -- IDX = lookup (TABLE, Y, OPT)
error: called from
    print_usage at line 91 column 5
    ismember at line 116 column 10
    dsParseModelEquations at line 67 column 1
    dsCheckSpecification at line 350 column 6
    dsGenerateModel at line 155 column 14
    dsCheckModel at line 98 column 8
    dsSimulate at line 484 column 7
```

**Comment by jsherfey** [comment]
Is this a fundamental problem with using the "ismember" function Octave or
specific to the particular use case? i.e., have you had success
using ismember in other situations in Octave before?

**Comment by kupiqu** [comment]
I tested simple examples of ismember use and they work fine and the same in Matlab and Octave. I guess we will need to test the specific case of DynaSim

**Comment by kupiqu** [comment]
I see, the problem is using ismember with cell arrays. I will investigate this further...

**Comment by kupiqu** [comment]
Correction: the problem is using ismember with empty arrays. so we need to check for empty arrays beforehand
