### ISSUE TITLE
Do not save mat files version 7.3 for portability reasons... your view on this

### ISSUE THREAD

**Issue by kupiqu** [DynaSim/DynaSim#228]
Currently mat files are saved wth version 7.3, which is not Octave compatible:

```
getMatComment ~/Documents/DynaSimData/demos/demo_sPING_1/data/study_sim1_data.mat
ans = MATLAB 7.3 MAT-file, Platform: GLNXA64, Created on: Fri Sep 29 15:36:20 2017 HDF5 schema 1.00 .
```

Could we save mat files other than 7.3 by default for portability reasons? 
I guess we could always use 'try catch' for mat files >2GB, and then use 7.3...

**Comment by asoplata** [comment]
I think this was the main reason we started using v7.3 as a default: https://github.com/jsherfey/dnsim/issues/58 IIRC, the data size limitations without using 7.3 were extremely limiting. 

That said, this shouldn't be hard to add as an option, like what @kupiqu suggested. **We could also add an option that the 7.3 flag is simply removed if Octave is being used, rather than Matlab.**

IMHO, the default *should* be 7.3, since 

1. most people will be using Matlab, not GNU Octave
2. common DynaSim use cases and even just moderately long simulations will fail,
3. similarly, we shouldn't expect the average user to have to understand MAT file format differences/limitations
4. in the event of failure to save or reaching an error (if 7.3 were not the default in the second case above), DynaSim's current error handling is minimal and nonexistent in many places, so we'd have to specify add error handling to make it clear.

**Comment by kupiqu** [comment]
Sure, but why not trying saving other than 7.3 first inside a try-catch conditional?

The only reason to not doing it is because if it fails then it takes more time to save.

I agree on all the other things you said, but consider that even dsDemos fails running because it opens previously saved mat files, so portability is an issue.

Currently we cannot publish a paper saying we support Octave in DynaSim if even the demos of the paper don't work.

I guess we can do a hack to workaround the issue of the demos, but there is no portability of data between Matlab and Octave at all if we don't use try-catch...

**Comment by kupiqu** [comment]
for completeness, other mat versions have advantages compared to 7.3, like data compression, but yes, one cannot save beyond 2GB, which is important, no doubt of it

**Comment by kupiqu** [comment]
Of course, all what I'm saying would be transparent to the final user...

**Comment by asoplata** [comment]
That's a good point, and another reason to do try/catch is that Octave may add capability of the same flag in the future. A try/catch block should catch the error very quickly.

It's also a great point that we need to fix this if we want to claim DynaSim works with Octave out of the box.

**Comment by kupiqu** [comment]
Another extra reason would be porting data easily e.g. from matlab to python or rlang. Not sure to what extent these languages can load mat files saved as v7.3, I think they can't, but I may be wrong

**Comment by benpolletta** [comment]
Is there a way to check whether DynaSim is being run inside Octave? If so, I like the idea of having an "octave_flag", and if it's true, saving without v7.3. That way you don't slow down saving of files for people running in Matlab.

Also, we need to think of an alternative solution for large data sizes in Octave. The "octave_flag" could trigger saving less of the data, as well, although I don't know how exactly to handle that.

**Comment by kupiqu** [comment]
1. I am firmly against an octave flag. There is no need for it as this can be totally automatized and make the whole thing transparent to the final user (we don't want an Octave user to run code and get errors and then have to look documentation to realize there is such flag, so he starts using it).

2. Making v7.3 the default for saving is not my first option either because of the portability rationale above, but that is not my decision to make, but of all of us as a team (weighted if you like), which I will respect, of course. But note that if that is decided, dsDemos must be changed such a way it doesn't raise errors in Octave. Somebody will have to work on this before submission of the paper (or change its content to omit Octave is supported).

3. Here, I would certainly understand and welcome the use of a flag: matversion_flag

4. Consistent with my view, I would suggest putting any version but 7.3 as default, and then within try catch errors, (a) set the flag to 7.3 if needed, as well as (b) inform the user that this can be set at startup in dsSimulate, etc.

This way, all code and data becomes portable unless strictly needed or explicitly decided so: the code detects the need, raising a warning (and being able to work around having to do it more than once, if there are several save instructions).  

My 2cts

**Comment by kupiqu** [comment]
We could also highly recommend in documentation, even say so when running demos, that if someone is using matlab only and not interested in porting data to e.g. R or Python, then it is better to use matversion_flag to 1 (name of the flag can, and should, be changed to make it more explicit, but you get the point).

**Comment by kupiqu** [comment]
If we decide that v7.3 should be default, writing a matlab porting function that opens a mat file v7.3 and saves it v7 or below would also be interesting to have (valid for files that are < 2GB)

This would be useless for Octave users (that don't have access to Matlab) as they would not be able to use it anyway, but could be useful for Matlab users that want to port small amount of data to R/Python (as well as to Octave, although it's tricky to infer why a Matlab user would port from Matlab to Octave...)

**Comment by kupiqu** [comment]
In fact, Octave also has options to save files >2GB (the reason why there is no way to make this compatible with Matlab, I assume, comes from Matlab being closed, but that's another story...)

In any case we could save a flag as 1 by default for mat compatibility (or to 0 if we decided that it would be better to prioritize >2GB against portability), and try/catch would set it to 0 when needed (so it would use 7.3 for Matlab, and 'hdf5' for Octave, when striclty needed or desired).

**Comment by kupiqu** [comment]
Btw, please note that the limit of 2GB is applied to variables, not to the final size of the mat file. Sorry I was confusing this above.

**Comment by DynaSim** [comment]
I vote for using v7.3 as a backup in a try-catch block, for all the reasons
mentioned above. It also seems like the simplest solution.

**Comment by kupiqu** [comment]
Current status in dev is mat files are saved as v7, unless an error in a try/catch block is triggered (Var > 2GB), then depending on reportUI, mat file is saved as either v7.3 or hdf5

Yet to do: 

Flag to choose between portability-safe (v7) vs trycatch-safe (v7.3/hdf5). 

Also, once implemented: when portability is active, it should nevertheless be switched once a catch is triggered (to avoid triggering further catch's), given that portability is not guaranteed anymore.

**Comment by kupiqu** [comment]
Done (commit 78003278ef911ca5065877a84f1d706bb295e7c7)
