### ISSUE TITLE
dsVary2Modifications: connections in square brackets are split into separate populations

### ISSUE THREAD

**Issue by jsherfey** [DynaSim/DynaSim#229]
This works:
vary={'(A,B,A->B)','IC_noise',[10 20]};
mod_set=dsVary2Modifications(vary); mod_set{:}
   '(A,B,A->B)'    'IC_noise'    [10]
   '(A,B,A->B)'    'IC_noise'    [20]
It returns values for 2 sims, one for each param value.

This doesn't work correctly:
vary={'[A,B,A->B]','IC_noise',[10 20]};
mod_set=dsVary2Modifications(vary); mod_set{:}
It should return values for 6 sims, setting each param value to A then B then A->B.
Instead, it returns values for 8 sims, setting each param value to A then B then A then B:
    'A'    'IC_noise'    [10]
    'A'    'IC_noise'    [20]
    'B'    'IC_noise'    [10]
    'B'    'IC_noise'    [20]
    'A'    'IC_noise'    [10]
    'A'    'IC_noise'    [20]
    'B'    'IC_noise'    [10]
    'B'    'IC_noise'    [20]

The most likely cause seems that A->B is being split into A and B before the vary statement is expanded into a set of modifications for each simulation.

**Comment by benpolletta** [comment]
Yeah, I can. I was just waiting to figure out where to commit the fix.

**Comment by jsherfey** [comment]
Great. Commit the fix to either debug or dev.
