### ISSUE TITLE
Move all TODOs from code comments into Issues

### ISSUE THREAD

**Issue by asoplata** [DynaSim/DynaSim#23]
This will have the added benefit of better illustrating where some functions are still incomplete, etc.

**Comment by erikthered12** [comment]
IMO it's good to have them in code comments when more detail is needed in context.

**Comment by asoplata** [comment]
I've changed my mind in that most TODOs seem to be little adjustments that aren't worth a feature branch on their own, or are tiny, etc. Now that the code is more complete, we can disregard this issue.
