### ISSUE TITLE
Parameters Can't include #e# for pow 10

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#230]
when doing #e#, causes the parameter to become a string

**Comment by jsherfey** [comment]
That should work, actually. Indeed, the parameter does become a string, but
that only means DynaSim labels it a "fixed variable." Fixed variables are
still evaluated before simulation. The parameter is then stored in the
fixed_variables field of the model structure.

Example:

>> d=dsSimulate('dV/dt=@current+I;{iNa,iK}; I=.1e2');
>> d.model.parameters

ans =

  struct with fields:

         pop1_iNa_gNa: 120
         pop1_iNa_ENa: 50
    pop1_iNa_IC_noise: 0
        pop1_iNa_h_IC: 0
        pop1_iNa_m_IC: 0
           pop1_iK_gK: 36
           pop1_iK_EK: -77
     pop1_iK_IC_noise: 0
         pop1_iK_n_IC: 0
            pop1_Npop: 1

>> d.model.fixed_variables

ans =

  struct with fields:

    pop1_I: 10

**Comment by DynaSim** [comment]
In case it isn't obvious: evaluating '.1e2' produces 10 (double precision),
and it is the latter that is used during numerical integration and stored
in the model structure.
