### ISSUE TITLE
Could we delete (or rename) example.m?

### ISSUE THREAD

**Issue by kupiqu** [DynaSim/DynaSim#231]
example is a generic name, likely to conflict other functions elsewhere. Also, it doesn't seem especially important. Furthermore, it is shadowing a core function in Octave:

 ```
-- example ("NAME")
 -- example ("NAME", N)
 -- [S, IDX] = example (...)

     Display the code for example N associated with the function NAME,
     but do not run it.

     If N is not specified, all examples are displayed.
```

**Comment by kupiqu** [comment]
For the case it is not clear, I refer to this function DynaSim/functions/dependencies/Coverage/Coverage/example.m

**Comment by jsherfey** [comment]
What is "Coverage"?

**Comment by kupiqu** [comment]
Nobody knows, should we delete it? ;-)

**Comment by kupiqu** [comment]
This is what the coverage toolbox is about:

https://www.mathworks.com/matlabcentral/fileexchange/33972-coverage-report-generator

So: "This packages uses the profiler to generate a Cobertura-style XML coverage report"

Is anybody using it or want to use it in the next future? 

So far nobody even replies to comments in this issue. Whoever introduced it to DynaSim is completely missing...

**Comment by jsherfey** [comment]
I vote for renaming it. I can't find any functions that call it, and I
think it's only there as an example for users to learn from.

**Comment by kupiqu** [comment]
renamed to coverage_example.m in dd09e5d

**Comment by erik-roberts** [comment]
Coverage was for checking what % of the code the unit tests cover. It would spit out a number that would be made into a badge found [here](https://github.com/DynaSim/DynaSim/wiki/CI-Status). Currently the unit testing framework has not been updated so it's not being used presently, but it's nice code to have. Changed the example name is fine.
