### ISSUE TITLE
Use Read the Docs for documentation

### ISSUE THREAD

**Issue by DynaSim** [DynaSim/DynaSim#232]

**Comment by jsherfey** [comment]
Resolved in Pull Request #233

**Comment by jsherfey** [comment]
I moved some of the wiki documentation to Read the Docs: dynasim.readthedocs.org

Let's put all future documentation there.

Read the Docs creates the documentation using Sphinx from source files in the DynaSim repo. 

Currently, the source files are located on the dev branch in docs/sphinx, and the content is in reStructuredText format. Markdown is supported for hyperlinked files but NOT for files linked to from the Table of Contents. The lack of toctree support for Markdown in Sphinx is a major limitation, so most of the content will need to be in reStructuredText format. There is a workaround, however: you can take a Markdown file and convert it to reStructuredText using: pandoc ORIGINAL_FILE.md -f markdown -t rst -o OUTPUT_FILE.rst. That's how I prepared docs from the DynaSim wiki.

Working with Sphinx Table of Contents: http://www.sphinx-doc.org/en/stable/markup/toctree.html
reStructuredText Primer: http://www.sphinx-doc.org/en/stable/rest.html#rst-primer

**Comment by jsherfey** [comment]
readthedocs structure:
- introduction/index.rst: Getting started
    - introduction/installation.rst: Installation
    - introduction/examples.rst: Examples
- user/index.rst: User documentation
    - user/faq.rst: Frequency asked questions
    - user/function_reference.rst: Function reference
- developer/index.rst: Development
    - developer/contributing.rst: Contributing
    - developer/function_template.rst: Function template
