### ISSUE TITLE
Add info about the user who ran the DynaSim study

### ISSUE THREAD

**Issue by kupiqu** [DynaSim/DynaSim#239]
From RCR (responsible conduct of research) workshop's reading I realized that we need to add date and time to the saving data files. I ignore if we do that already, but that's something we must actually do. This should be very easy to implermet too, so there is no excuse.

One can say, it's in the creation of the file, but think that this metadata can be lost easily. The file can be copied or moved without careful keeping of the metadata, and then the information gets lost.

To know more about this, see for instance http://ori.dhhs.gov/education/products/RCRintro/c06/2c6.html

**Comment by kupiqu** [comment]
We could create a metadata field, with info about the user who ran the study, date, time, etc.

**Comment by kupiqu** [comment]
Everything but the user is already there...

**Comment by jsherfey** [comment]
Metadata is stored in studyinfo.mat when results are saved to study_dir.

I will add user metadata to studyinfo by:
(1) documenting machine_info.username in dsCheckStudyinfo(), and 
(2) setting it in dsUpdateStudy() using studyinfo.simulations(sim_ind).machine_info.username = getenv('USER').

**Comment by jsherfey** [comment]
Edit: I added user info to studyinfo.user_name in dsCheckStudyinfo() (i.e., instead of machine_info) because all simulations in a batch are necessary launched by the same user.

Issue resolved in commit 1f81d1d8749358e627d8beb2c6b9f5768e1fa720.
