### ISSUE TITLE
Clarify/customize installation procedure for DynaSim

### ISSUE THREAD

**Issue by asoplata** [DynaSim/DynaSim#24]
## Installation

So I just tested trying to **globally** install DynaSim on the SCC cluster that we use and remembered how much trouble I'd had the last time with installing DNSIM. Thankfully, I got it to work, and I think I understand how!

All you need to do is make a `startup.m` file in your `~/Documents/MATLAB` directory (make the directory if you don't already have one). Simple add `addpath(genpath('/your/path/to/dynasim'))` to `~/Documents/MATLAB/startup.m`, where the directory mentioned is your git-cloned copy of the `dynasim` repo. For example, my `startup.m` is just

```
addpath(genpath('~/x014-dynasim-development/dynasim'))
```

This seems to work however I've tested it: from an ssh terminal via the GUI, on the desktop via VNC, etc. @jsherfey does anyone know a situation in which this wouldn't work? I've tested it as far as I can and it's the ONLY solution I've found that seems to work _no matter which directory your MATLAB session is started from_.
## TODO

**I suggest that we make this the default installation method for DynaSim**, as the traditional `Set Path` method does NOT seem to work on the SCC cluster:
## Why use `startup.m` for adding to the MATLAB path instead of the regular `pathdef.m` way

Short version: MATLAB paths using the preferred `USERPATH/pathdef.m` aka `~/Documents/MATLAB/pathdef.m` file are broken on the cluster.

Abandon all hope, ye who enter here: the different `pathdef.m` files, `USERPATH` via entering the `userpath` command, the `path` command, etc. all seem to be problematic and do not work globally. Due to the fact that the MATLAB install on the cluster is a little quirky, you can find all the `pathdef.m` files your MATLAB is using with `which pathdef -all`. This should give you one or two files: the "core" one at `/usr/local/apps/matlab-2013a/toolbox/local/pathdef.m`, which is administered by the cluster, and possibly (if you have one), another at `...homefolder.../Documents/MATLAB/pathdef.m`. This latter file is located in [what MATLAB calls the `userpath`](http://www.mathworks.com/help/matlab/ref/userpath.html), which AFAIK should be `~/Documents/MATLAB`; you can see your `userpath` by just typing `userpath` into the MATLAB Command Window.

The absolutely infuriating problem with this is, even if you save your DynaSim directory and all its subfolders to your `~/Documents/MATLAB/pathdef.m`, **`~/Documents/MATLAB/pathdef.m` is not always read at startup!** Despite being the main, recommended way to add to the MATLAB path at startup AFAIK, if you start a MATLAB session anywhere else, like in `~/Videos`, the code in custom paths/subfolders/etc. you have manually added to your custom `pathdef` will not be on the path in this new session! Confusingly, if you run `which pathdef -all` ([as shown in the docs here](http://www.mathworks.com/help/matlab/matlab_env/when-path-not-successfully-set-at-startup.html)), it will say your local `pathdef.m` is detected, and because it's the topmost `pathdef` file it should outrank the others, but then if you run `path` you'll see that your path does NOT include some of the entries listed **in that same file!** UGH it's enough to make someone go crazy.

Then you notice that the top directory in the path seems to be `~/Documents/MATLAB`, okay, well it's not quite there but we can try to work with that...

So you think, "let me make it easier for MATLAB and insert a symbolic link inside `~/Documents/MATLAB` to go to my code folder, then add that symbolic link to the MATLAB path". Either my local `~/Documents/MATLAB/pathdef.m` file will now be read correctly, or at LEAST because the code is now _directly linked to inside my `~/Documents/MATLAB` directory, surely it must be included in the path now!_ But you're still wrong -- if you start a MATLAB session not in your DynaSim directory nor in `~/Documents/MATLAB`, then it STILL won't have added the DynaSim directory to your path.

This is where you start to think "This is getting a little ridiculous. Whatever, I'll just put the code itself in `~/Documents/MATLAB/dynasim`!" So you copy the `dynasim` directory into `~/Documents/MATLAB`, and just to be sure you add it and all its subdirectories using the MATLAB GUI's "Set Path", then restart MATLAB...only to find out this STILL doesn't let you run your code when MATLAB is started anywhere else!

At this point, because `~/Documents/MATLAB` is always in the path, I tried putting `SimulateModels.m` by itself in the folder and wa-la! `SimulateModels` is recognized in the namespace! This means that you CAN put individual files in the userpath folder `~/Documents/MATLAB` and they will be read anywhere, but if those files are in a subdirectory inside said folder, they will not be seen...even though there's a correct `pathdef.m` inside that very same folder.

I want to point out again that in all these cases, **even though `which pathdef -all` shows MATLAB is reading/seeing `~/Documents/MATLAB/pathdef.m`, it does not appear to EVER be actually using it!**

Note that these scenarios have also been tested out when putting `pathdef.m` right at my `$HOME` or `~` directory in some vague hope that that would work. Not only does that never work, but MATLAB, in this case true to the documentation, doesn't find `~/pathdef.m` if you've started a MATLAB session anywhere else like `~/Videos`.

It seems the only way to utilize `~/Documents/MATLAB/pathdef.m` is to start MATLAB from inside that directory...which defeats the point of trying to save additional paths for a user to a single location. Note that in the documentation, this is the default starting Working Directory upon MATLAB startup when you start MATLAB on Windows or Mac...but nothing is said about Linux.

If you remove your `~/Documents/MATLAB/pathdef.m`, then start MATLAB, add something to the path, then try to save the path, you get a prompt asking you where to save it. It seems that if you save the new `pathdef.m` ANYWHERE except `~/Documents/MATLAB`, then upon starting up a new MATLAB session, (unless there is a `pathdef.m` in the directory you started the session in), that `pathdef.m` file you just saved is not seen. Only a `pathdef.m` file inside `~/Documents/MATLAB` is automatically detected at startup...even though it's not actually fully processed! Furthermore, if you have a `~/Documents/MATLAB/pathdef.m`, then when you add something to the path permanently, _the path additions are saved to that file by default -- it doesn't prompt you for a filename at all -- but upon starting another MATLAB session anywhere except `~/Documents/MATLAB`, the file you just automatically wrote to is not read_! Even though the path additions are saved there by default! **THIS in particular is what makes me think this is legitimately a MATLAB bug**, although it could be a product of some weird install by the cluster people.

I tested the basic problem on MATLAB 2014b, so this is still happening. While this _could_ be by design, since limiting the amount of stuff in the global namespace is, in general, good coding practice, both that philosophy contrasts with MATLAB's general approach, and on Windows/Mac, the default is to start MATLAB instances in `~/Documents/MATLAB`, which would then load the namespaces of that folder's `pathdef.m` -- in other words, the standard for `userpath` `pathdefs.m` would be unique to Linux by default, and different than other OS's. Therefore, I don't think this is by design, and is instead a bug. I'm going to file a bug report with the cluster and MATLAB unless someone explains how I'm wrong.

**Even if there's a certain way by which using `pathdef.m` to add to the MATLAB path DOES work on the cluster, there are so many ways where it's _supposed_ to work that don't, that it's effectively broken.**

For using interactive MATLAB, adding the path like I do above into `~/Documents/MATLAB/startup.m` seems to do the job. Where the individual batch jobs read from on startup is a bigger question, but because those jobs are already calling DynaSim correctly, Jason's use of `addpath` inside the DynaSim code itself seems to solve that issue! Thank goodness.

**Comment by asoplata** [comment]
Just to clarify, none of this would be a problem if we weren't running MATLAB, including its root startup `pathdef.m` file etc., from read-only administrative locations due to the cluster. If it's your own personal laptop/version of MATLAB, then you should have access to MATLABROOT, which can be printed by entering `matlabroot` at the command window; inside that directory will be the default `pathdef.m`. If you have write access to that file, which you most certainly do if you installed MATLAB locally, then any paths you add to MATLAB are probably contained in that and will be properly interpreted.

Still, due to the fact that that install method will NOT WORK on the SCC cluster, for the general use of DynaSim, I think we should use the `~/Documents/MATLAB/startup.m` method I described above, as that should work for EVERYONE.

**Comment by asoplata** [comment]
Omg I got an answer on the Mathworks site! http://www.mathworks.com/matlabcentral/answers/269482-is-userdata-pathdef-m-for-local-path-additions-supported-on-linux#answer_210839 It appears that using a second `pathdef.m` does not work by design, meaning that using a `~/Documents/MATLAB/pathdef.m` won't work for us on the cluster. Thankfully `~/Documents/MATLAB/startup.m` does.

**Comment by jsherfey** [comment]
I think the only installation procedure should be: download toolbox, add <dynasim>/functions to matlab path. Model files should be located in the current working directory or in <dynasim>/models.

**Comment by asoplata** [comment]
Note: Jason, don't worry about responding to any issue updates like this/etc. until quals/CRC obviously!

My point from the above is that, on the SCC cluster, we cannot add things permanently to the MATLAB path using the default `pathdef.m` way, and instead must hack it using `~/Documents/MATLAB/startup.m` in order for code in the path to be accessible no matter where you start DynaSim...if we even want that. Note that this isn't disagreeing with what you stated.

To move any further on this, we need to have a discussion about Workflows, and that means Model Management. This is a discussion we really should have in person. But just for a taste, I mean: should you only have access to the models in the current `model` subdirectory, which would do a good job of compartmentalizing between the model directories of different project, but forces you to start MATLAB/DynaSim in specific directories? Or, instead, support use of subdirectories of models in the `models/` subdirectory, such that you can have project-specific subdirectories, and ALL mechanisms are on the universal MATLAB path at all times (this works and is accomplished by the `startup.m` install method mentioned above)? More plainly, if I want to use the model sets of several different projects (including easily downloading others and using them), what is the recommended way to do this? That's what we need to figure out still.

**Comment by asoplata** [comment]
This needs to be updated to make installation compatible with the new usage of `git submodule`.

**Comment by asoplata** [comment]
Done! [This is now on the wiki](https://github.com/DynaSim/DynaSim/wiki/Installation). Yay! 
![cat-programmer](https://cloud.githubusercontent.com/assets/661173/25967324/c4e257c2-365b-11e7-90af-593937067546.jpeg)

**Comment by erik-roberts** [comment]
when you say the pathdef way, was right clicking and adding to path tried as well?

**Comment by asoplata** [comment]
Yes, that was tried. Upon doing so, the item to add would get added to the
path in that session, but would be lost again if you opened a new Matlab
session. I tested a lot of different possibilities, and the one we settled
on is the only way you get reliable pathing no matter where you start
MATLAB, and it works every time (other than adding our own path handling
into the code, but then you need to add in how the user customizes the
location etc. - e.g. if user starts in a random directory, they still have
to pass in their path to their dynasim in their own code, since that is a
major assumption).

AFAIK, Using the startup file is the ONLY way to permanently add your own
code onto the path, if using MATLAB on the cluster.

**Comment by erik-roberts** [comment]
dang. one issue i had was my startup was too full, so i started making a separate startup file that i call in an alias when running non-batch matlab.

**Comment by erik-roberts** [comment]
we need install instructions for a zip file too.

**Comment by jsherfey** [comment]
This has been clarified in ReadTheDocs documentation: http://dynasim.readthedocs.io/en/latest/introduction/installation.html
