### ISSUE TITLE
Set up mailing lists without Google Groups

### ISSUE THREAD

**Issue by jsherfey** [DynaSim/DynaSim#243]
We need to move to Google-independent mailing lists to make them accessible to more people.

They could be hosted on a BU server or a free online service.

**Comment by erik-roberts** [comment]
something to look into:
https://www.gnu.org/software/mailman/features.html

**Comment by erik-roberts** [comment]
https://www.bu.edu/tech/services/cccs/email/mailing-lists/

**Comment by jsherfey** [comment]
Majordomo mailing lists hosted by Boston University:

Subscribe by emailing majordomo@bu.edu: subscribe dynasim-developers-list
Post to list by emailing dynasim-developers-list@bu.edu

Subscribe by emailing majordomo@bu.edu: subscribe dynasim-users-list
Post to list by emailing dynasim-users-list@bu.edu

Owned by @jsherfey

**Comment by erik-roberts** [comment]
didnt we switch back to google?
