### ISSUE TITLE
Consider changing the convention for linking with @current

### ISSUE THREAD

**Issue by jsherfey** [DynaSim/DynaSim#244]
At present, ionic mechanisms are linked using dV/dt=@current/C with @current += -Iion(...); so, @current actually refers to -(ion current). Perhaps we should change the convention or conductance-based models to be: dV/dt=(@input-@current)/Cm with @current += Iion(...) in ionic mechanisms and @input += Iext(...) for external drives. This would require updating *.mech, *.pop, demos, and the paper. It will break anyone's existing code that depends on the default mechanisms in the models directory.

**Comment by kupiqu** [comment]
It's quite a mess to change this now, but it's more proper and better now than later

**Comment by erik-roberts** [comment]
since the currents are actually positive by convention (i think), and the negative just comes from moving the term to the RHS of the equation, that makes sense to change it.

**Comment by erik-roberts** [comment]
people are just going to copy the demo and existing mechanisms so that will help things.  just make sure the monitor goes the expected direction.

**Comment by jsherfey** [comment]
Moved minus sign from linker to function and left everything else the same.

Issue resolved in commit 9449c964db3017d65a17811eaa502cffd5598420.

**Comment by asoplata** [comment]
I'm confused as to the actual behavior of what's going on now. If, for example, all the mechanism contributions to `@current` are positive, and the usage of `@current` in the `eqns` is also positive like in the following section of the demos:

```
data=dsSimulate('dv/dt=10+@current/Cm; Cm=1; v(0)=-65; {iNa,iK}');

figure; plot(data.time,data.(data.labels{1}))
xlabel('time (ms)'); ylabel('membrane potential (mV)'); title('Hodgkin-Huxley neuron')
```

then shouldn't the above code NOT work correctly? I thought that, under this new convention, you would have to change the `dV/dt` mention of `@current` to be negative, NOT positive?

If the above code is correct, then doesn't this imply that DynaSim is really using negative `@current` even when I'm telling it I want positive `@current`? In other words, is `@current` being forced to be negative now? If this is the case then that seems like a hidden pattern.

**Comment by DynaSim** [comment]
The new convention is to put the minus sign in the function definition.

e.g.)

IL = - gL*(V-EL)
@current += IL
dV/dt = @current+10; {IL}

**Comment by asoplata** [comment]
Ahhhhh okay, I get it. When Jason said he moved the minus sign to the function, I got really worried that he moved it to be automatically added/parsed in a DynaSim function! Glad to see this wasn't a functionality change. Thanks for clarifying
