### ISSUE TITLE
Add predefined networks and multicompartment neurons

### ISSUE THREAD

**Issue by jsherfey** [DynaSim/DynaSim#246]
Create predefined networks and pops of multicompartment neurons (e.g., support m-file defining multi-compartment specification, and mat-file containing a multi-compartment specification; concatenate structures in dsCheckSpecification). 

Simple approach:
- Create dsCombineSpecifications(): concatenate pops, cons, and .mechanisms from two specifications
Example: combine my PFC model with Austin's thalamic model
   s1=get_thalamus('awake'); % given function: get_thalamus.m
   s2=get_PFC('DS02');         % given function: get_PFC.m
   s=dsCombineSpecifications(s1,s2);
   s=dsApplyModifications(s,{'PYa->TC','mechanism_list','+iAMPA'});
   s=dsApplyModifications(s,{'TC->PYd','mechanism_list','+(iAMPA,iNMDA)''});
AND
   s1=getfield(load('thalamus_awake.mat'),'specification');
   s2=getfield(load('PFC_DS02.mat'),'specification');
   ...

OR (equivalently) --

More complicated approach using a single specification structure:
- Create isfunction(): https://blogs.mathworks.com/loren/2013/08/26/what-kind-of-matlab-file-is-this/
- Create dsCheckSpecification/findspecinscript(file): run(file); vars=who; for var in vars: if isfield(var,'populations'), s=var; end
- in dsCheckSpecification: if .eqns == 'file.m', if isfunction('file'), s2=eval('file'); else s2=findspecinscript('file'); end; elseif .eqns == 'file.mat', s2=getfield(load('file.mat'),'spec'); end; s=dsCombineSpecifications(s,s2)
- Need to support setting s.pops.eqns to a full specification. e.g., s.pops(i).eqns=get_cell('DS02PYjs',100). approach: remove pops(i) then concatenate s and pops(i).
Example: combine my PFC model with Austin's thalamic model
    s.pops(1).eqns=get_thalamus('awake'); % returns full specification for the awake thalamic network
    s.pops(2).eqns=get_PFC('DS02');  % returns full specification for the prefrontal network with multicompartment cells
    s.cons(1).direction='PYa->TC';
    s.cons(1).mechanism_list='iAMPA';
    s.cons(2).direction='TC->PYd';
    s.cons(2).mechanism_list={'iAMPA','iNMDA'}.

**Comment by jsherfey** [comment]
The "simple" approach was implemented in Pull Request #341

The "complicated" approach has not been implemented yet (may not need to be...).

**Comment by erik-roberts** [comment]
this is all in https://github.com/DynaSim/DynaSim/wiki/Combining-models right?
