### ISSUE TITLE
rename qmatjobs_* files to qjobs_* and make them work both in matlab and octave

### ISSUE THREAD

**Issue by kupiqu** [DynaSim/DynaSim#249]
I need to pass 'matlab -nodisplay -singleCompThread' vs 'octave-cli' as an extra argument, and in the case of octave, also add '-l centos7=TRUE'

**Comment by kupiqu** [comment]
Jason, are qmatjob_array and qmatjob_one_file in use? what am I supposed to do with them...?

**Comment by jsherfey** [comment]
`qmatjob_array` and `qmatjob_array_one_file` were created by @erik-roberts for use with the options 'qsub_mode' and 'one_solve_file_flag'. 

Erik, do these features work? Can the submission scripts be consolidated?

Salva, if the scripts cannot be consolidated, the same approach for achieving Octave compatibility should be applied to each of them.

**Comment by jsherfey** [comment]
Consolidation would mean combining all the submission scripts into one file (including `qmatjob_array`, `qmatjob_array_one_file`, `qmatjob_loop`, `qmatjobs_memlimit_loop`, and the new Octave-compatible versions). This might be possible using additional arguments to direct the single submission script based on 'qsub_mode' and 'one_solve_file_flag' in `dsCreateBatch` and whether using Matlab or Octave.

**Comment by kupiqu** [comment]
I see


--

Enviat des del telèfon

**Comment by jsherfey** [comment]
Consolidating them in that way could reduce code duplication and
inconsistencies (e.g., like using hard-coded Matlab path in `qmatjob_array`
and the user's default version in `qmatjob_loop`).

**Comment by kupiqu** [comment]
Certainly, consolidating is the ultimate purpose of this issue, although originally I was only aware of `qmatjobs_memlimit_loop` and `qmatjob_loop`...

**Comment by kupiqu** [comment]
Keeping this issue open because consolidation was not done at this time

**Comment by erik-roberts** [comment]
> Jason, are qmatjob_array and qmatjob_one_file in use? what am I supposed to do with them for Octave compatibility...?

these are for submitting using array mode with multiple files, and for submitting with array mode and one file mode. consolidation is tricky since they each take different arguments. we'd have to do some logic in the script and pass a first variable saying which of the 3 types is desired.

**Comment by erik-roberts** [comment]
When done, update the wiki page: https://github.com/DynaSim/DynaSim/wiki/Cluster-usage

**Comment by erik-roberts** [comment]
done with this for array. also cleaned up the qsub files. added multicore for matlab using `-pe omp #`.

**Comment by erik-roberts** [comment]
the version of matlab called corresponds to the terminal version of matlab from which the commands were submitted.

**Comment by erik-roberts** [comment]
for some reason, i see a splash screen in vnc for each submission.

**Comment by kupiqu** [comment]
> for some reason, i see a splash screen in vnc for each submission.

you can use -nosplash to avoid the spash screen

**Comment by erik-roberts** [comment]
branch is iss249_array
