### ISSUE TITLE
Collate required transitional changes to DNSIM mechanisms...or just update everything

### ISSUE THREAD

**Issue by asoplata** [DynaSim/DynaSim#25]
In order to take an old DNSIM mechanism and turn it into a DynaSim mechanism, there are a few changes that must be made -- however, over the last hour, I've found some more discrepancies between the two formats that are undocumented.

From the current Tutorial.m, there is some help in converting mechanisms:

``` matlab
%% Converting models from DNSim to DynaSim

% Replace function calls: buildmodel() by GenerateModel(); runsim() by 
% SimulateModel(); simstudy() by SimulateModel() with (scope,variable,values) 
% reorganized and passed as modifications={scope,variable,values; scope,variable,values; ...}.

% Each variable/monitor now has dimensions [data] = time x cells.  
% Previously was [data]=cells x time
% Now, connection matrices: [netcon]=(Npre x Npost).

% Therefore, in each DNSim connection mechanism, transpose the connectivity 
% matrix and replace (netcon*s) by (s*netcon).

% Example: in <dynasim>/models/legacy/sPING
% Compare
%   AMPA.txt  -- prepared for DNSim
%   AMPA2.txt -- edited for DynaSim

% Everything else should be back-compatible.
```

However, in addition to this, I tried substituting in [my own iNa_TC.txt](https://github.com/asoplata/ching2010_tcre_mechanisms/blob/master/database/iNa_TC.txt) file in place of a regular `iNa.mech` mechanism in one of the Tutorial examples. I found three additional things need to be changed in order for my DNSIM mechanism to even be run at all, without error:
1. Need to change `iNa_TC.txt`'s state variable `V` to `X`: seems `V` in older mech files doesn't work anymore, probably because `V` is a special case for voltage now.
2. Need to change `current => -iNa_TC(V,mNa,hNa)` to `@current += -iNa_TC(V,mNa,hNa)`: I get an error with "Unbalanced or unexpected parenthesis or bracket" for the former old style. This may only be happening because this is the first mechanism cited in the main dV/dt equation in the solver, but it doesn't matter -- if it doesn't work, it doesn't work, and therefore the usage of `current` in mechanism files should be transitioned to the new form just in case.
3. Need to remove underscores in mechanism names, so `iNa_TC.txt` becomes `iNaTC.txt`: DynaSim seems to confuse the namespaces, e.g. I get an "no iNa_Npop found" error when using mechanism file `iNa_TC.txt`, but not when I change the filename to `iNaTC.txt`. This may only be a problem for the filenames of mechanisms, instead of what's the actual mechanism contents, as my variable inside `iNaTC.txt` was still `iNa_TC` and it still ran...but because there's a limitation on either, and we certainly want the filenames to match the mechanism names, this effectively acts as a limitation on mechanism names -- no underscores anymore!

Because it is definitely nontrivial to change old DNSIM mechanisms into DynaSim-compatible ones now, we should either
1. Make a master list of the transitions needed to turn DNSIM mechanisms into DynaSim ones, or...
2. Since there's only so many DNSIM mechanism files around, really, we should 
   1. make a point of **only supporting the new format**, 
   2. upgrading all the old ones we can find ourselves and making it clear they're the canonical version now, and 
   3. helping anyone who still has old DNSIM mechanism files to transition them to DynaSim compatbility upon request.

I say we do 2, because we'll never know if we're keeping track of ALL the differences between mechanism compatibilities, and DNSIM is effectively deprecated anyways.

**Comment by asoplata** [comment]
More transitional changes:

4. In synaptic mechanisms, what were `Npre` and `Npost` before are now `N_pre` and N_post`. 
5. Additionally, substitution of the input/output state variables (formerly `IN` and `OUT`) in synaptic mechanism files are now different, in that, in functions, you use `X` where you used `IN` before, in ODEs you use `X_pre` where you used `IN` before, and in the linkers (e.g. `@current += ...`) you use `X_post` where you used `OUT` before.

I'm basing all of these changes from what I've observed in the current `iAMPA.mech` etc. files in the `models/` subdir of DynaSim.

**Comment by jsherfey** [comment]
I agree we should convert old mechanisms into the new format. You listed a couple changes that should  not be necessary though. For instance, replacing 'V' by 'X' and 'Npop' by 'N_pop'. More to come...

**Comment by asoplata** [comment]
Note: Jason, don't worry about responding to any issue updates like this/etc. until quals/CRC obviously!

1. I struckthrough my comment above about `N_pre` in synaptic mechanisms, as you're correct when it comes to `Npre` and `Npost` in synaptic mechanisms: I just tested this and it appears they don't need to be changed. Stylistically, all the mechanisms I've seen intended for DynaSim use use underscores like `N_pre`, so while it's a good idea to be on the same page stylistically, functionally no one needs to replace `Npre` etc.
2. I ran into the `Error: Undefined function or variable 'V'` both when I was first transitioning my DNSIM-compatible mechanisms over, and upon additional tests just done after updating to the most recent version: not using `X` is still a problem. E.g., if you take an example from the tutorial that uses the [iNa.mech mechanism](https://github.com/DynaSim/DynaSim/blob/master/models/iNa.mech) like 
```{matlab}
eqns={ 
  'dv/dt=Iapp+@current+noise*randn(1,N_pop)';
  'monitor iGABAa.functions, iAMPA.functions'
};
% Tip: monitor all functions of a mechanism using: monitor MECHANISM.functions
time_end = 100; % ms?

% create DynaSim specification structure
s=[];
s.populations(1).name='E';
s.populations(1).size=80;
s.populations(1).equations=eqns;
s.populations(1).mechanism_list={'iNa','iK',...
                                 'CaBuffer','iCan',...
                                 };
s.populations(1).parameters={'Iapp',5,'gNa',120,'gK',36,'noise',40};
s.populations(2).name='I';
s.populations(2).size=20;
s.populations(2).equations=eqns;
s.populations(2).mechanism_list={'iKDR','iM','iNaF'};
s.populations(2).parameters={'Iapp',0,'gNa',120,'gK',36,'noise',40};
s.connections(1).direction='I->E';
s.connections(1).mechanism_list={'iGABAa'};
s.connections(1).parameters={'gGABAA_base',.1,'netcon','eye(N_pre,N_post)'};
s.connections(2).direction='E->I';
s.connections(2).mechanism_list={'iAMPA'};
s.connections(2).parameters={};

vary={
  'E'   ,'Iapp',[10];      % amplitude of tonic input to E-cells
  };

SimulateModel(s,'save_data_flag',1,'study_dir','demo_cluster_1',...
                   'vary',vary,'cluster_flag',0,'verbose_flag',1,...
                   'overwrite_flag',1,'tspan',[0 time_end])
```

and replace all usage of `X` in 'iNa.mech' with `V`, then the simulation DOES NOT RUN, and instead gives that error mentioned above. Looking at the error mentioned in the generated Solve script, the problem seems to be that `V` is not replaced with the voltage state variable, in this case `E_v_k1`. I also tried `P` which gave the same thing, I tried replacing ALL `X` state variables in all mechanisms for a particular population with `V` and it didn't work, and curiously when replacing `X` with lowercase `v`, it DID work -- the lone `v` WAS substituted correctly in the resulting, generated solve script.

This maybe wasn't the intention, but as far as I can tell, if you're using a substituted / "main" state variable like `V` or `v` worked before in DNSIM, **right now, the only way that works is `X`** (or `v` if that's what is being used in your `eqns`). This is probably a real bug instead of by design.

**Comment by asoplata** [comment]
This is probably no longer needed.
