### ISSUE TITLE
all saving should use -v7 format by default for compatibility reasons

### ISSUE THREAD

**Issue by kupiqu** [DynaSim/DynaSim#251]
as far as I can see, this needs to be applied to:

dsCreateBatch.m
dsStudyinfoIO.m
dsWriteDynaSimSolver.m
dsWriteMatlabSolver.m

**Comment by erik-roberts** [comment]
is there an option for -v7.3? this is important for larger files.

**Comment by kupiqu** [comment]
It is, and it is documented in dsDemos.m

**Comment by jsherfey** [comment]
It is also documented online in the wiki in the "Getting started" tutorial:
https://github.com/DynaSim/DynaSim/wiki/DynaSim-tutorial
