### ISSUE TITLE
GPU computing

### ISSUE THREAD

**Issue by jsherfey** [DynaSim/DynaSim#26]

**Comment by erik-roberts** [comment]
what's the status with this?

**Comment by jsherfey** [comment]
By "GPU computing" I meant using the Parallel Computing toolbox to run
multiple simulations in parallel. Dave has implemented that. It is
impossible to parallelize the numerical integration of arbitrary ODEs.
Parallelizing a single simulation requires event-based synapses and is only
beneficial for networks with certain spike statistics.

**Comment by erik-roberts** [comment]
where did dave implement it? is it documented?

**Comment by jsherfey** [comment]
In dsDemos and here:
https://github.com/DynaSim/DynaSim/wiki/High-performance-computing#parallel-computing
(this needs to be made more readable)
