### ISSUE TITLE
How to set a proper environment in SCC

### ISSUE THREAD

**Issue by kupiqu** [DynaSim/DynaSim#260]
Edit your bash profile `~/.bash_profile` in SCC (all nodes will see that environment):

- For Matlab add: `module load matlab/2014a` (example for using Matlab 2014a, adjust it to your preference!)

- Current stable version (Octave 4.2.1) requires centos7 nodes. Therefore, for Octave add:
  ```
  module use /share/module/centos7
  module load octave/4.2.1
  ```

The way to access centos7 nodes manually is by adding the directive `-l centos7=TRUE`, so you can connect to a node like this: `qrsh -l centos7=TRUE`

I made changes in DynaSim, so it manages that for you transparently when submitting loop batches (it remains to be done for the array and array_one_file; see issue #249).

I hope this is useful for keeping always the right matlab version everywhere and for easing testing DynaSim functionality in Octave.

**Comment by erik-roberts** [comment]
@kupiqu can you move this to the wiki please?

**Comment by kupiqu** [comment]
Sure...

**Comment by kupiqu** [comment]
Done, it appears in the Cluster Usage page

**Comment by erik-roberts** [comment]
Thanks!
