### ISSUE TITLE
Add support for 2D populations

### ISSUE THREAD

**Issue by jsherfey** [DynaSim/DynaSim#264]
This is necessary for simulating approx PDE-type models (e.g., reaction-diffusion equations). 

The goal is for something like this to work:
```
s.pops.size=[300 300];
s.pops.equations={'dA/dt=da*del2(A)-A.*B.^2+f*(1-A); A(0)=A_IC';
                  'dB/dt=db*del2(B)+A.*B.^2-(k+f)*B; B(0)=B_IC'};
s.pops.parameters={'da',da,'f',f,'db',db,'k',k,'A_IC',A,'B_IC',B};
data=dsSimulate(s,'dt',dt,'tspan',[0 stoptime]);
dsPlot2D(data); % display movie
```

**Comment by jsherfey** [comment]
This issue was resolved in Pull Request #265.

**Comment by erik-roberts** [comment]
@jsherfey is this documented somewhere?  would be good to add a how to also.

**Comment by jsherfey** [comment]
Sort of:
The example section of DynaSim wiki (https://github.com/DynaSim/DynaSim/wiki)
points to two scripts that demonstrate the functionality:
https://github.com/DynaSim/DynaSim/blob/master/demos/examples/dsReactionDiffusion2D.m
https://github.com/DynaSim/DynaSim/blob/master/demos/examples/dsShuntingNetwork2D.m

However, more informative comments should be added to those scripts; and/or
they could be converted into separate wiki pages with better documentation.
