### ISSUE TITLE
Remove dsConfig.txt from repo

### ISSUE THREAD

**Issue by kupiqu** [DynaSim/DynaSim#268]
It gives an error at first install, so the final user first needs to manually delete it, so DynaSim creates a new (non-buggy) dsConfig.txt file, which is system specific.

We should also add that file to .gitignore so once a new dsConfig.txt is created, git does not care about it.

**Comment by erik-roberts** [comment]
i think this is already fixed as i don't see the file in the repo and it's in gitignore so closing.
