### ISSUE TITLE
SCC Mex Compilation

### ISSUE THREAD

**Issue by asoplata** [DynaSim/DynaSim#27]
The Problem: Recently, the SCC people decided to limit the number of simultaneous MATLAB licenses (including Toolboxes) that any one user can use...to **one**, a single one! Yes, that means that under the new rules, new as of at least this year but probably only in the past two weeks, you _technically_, can only have one MATLAB job running at a time on the SCC cluster, **unless you're running compiled MATLAB code, which doesn't inherently use licenses**. Thankfully, the generous SysAdmin gods of the cluster are letting people violate this limit by letting them use 3-5 licenses at a time, or potentially more, but ONLY IF there is not heavy use of the licenses by the university as a whole; if license usage is high, they will mercilessly kill your MATLAB jobs to free up licenses.

The Solution: There has been some discussion and many emails from myself on this, but the SCC-recommended way to deal with this problem is to enable compilation of jobs on the cluster. The only fullproof way to do this for DynaSim-type parallelization is: for some batch of jobs, have a SINGLE compilation that will enable simulation, analysis, AND plotting for N jobs. AFAIK, any other way I've tried to figure this means that you're still forced to use either N simultaneous MATLAB licenses or you start doing things serially, which is unacceptable IMO. There are theoretically some alternatives to this (like building a DynaSim style system around Brian2 as a Python simulation engine), and most of those are included in some of my emails to the DynaSim group that no one read, but while this is still going to be a decent amount of work, this is probably what we're going to end up doing for obvious reasons.

Based on my testing, playing around with the MCR compiler etc., the best approach I'm thinking is to piggy-back on the current very-many `sim_jobN.m` files (where N is the identifying number of a job in a single batch) and instead make only a single `sim_job.m`-style file that will be compiled using either MEX or MCR, then fed (via the CLI) what few things actually changed between `sim_jobN.m` files -- namely, the `SimIDs`. AFAIK, what actually differentiates individual sims is really **only** the `SimIDs`, since that variable seems to be the only, or at least main, thing changed between said files, and is also used as the identifier of which `studyinfo_N.mat` is integrated to parametrize the actual simulation. In other words, it may not be too much work to change the system over to that of: each job consists of a single executable that takes some number N which decides which of very many `studyinfo_N.mat` files to use to run the simulation.

This assumes we'll have to write new bash code of course, and changes especially to `CreateBatch.m`, nevermind the fact that it'll be slow journey through the jungle of serially finding out what parts of the entire code to be compiled either A. are not allowed to be compiled or B. can be compiled, but then _run differently_ in the compiled version. It'll be a lot of work.

**Comment by erikthered12** [comment]
Duplicated in #96

**Comment by erikthered12** [comment]
@jsherfey says this works. @asoplata @davestanley
