### ISSUE TITLE
A recent change in dsPlot broke Octave execution

### ISSUE THREAD

**Issue by kupiqu** [DynaSim/DynaSim#271]
```
error: data(1): out of bound 0  
error: called from  
    dsCheckData at line 59 column 1  
    dsPlot at line 261 column 5  
    dsDemos at line 301 column 1
```

**Comment by kupiqu** [comment]
Actually it seems it is in dsCheckData :/

**Comment by jsherfey** [comment]
No changes to the function dsCheckData have occurred since June, according
to
https://github.com/DynaSim/DynaSim/commits/dev/functions/internal/dsCheckData.m

**Comment by kupiqu** [comment]
I checked the code was working just fine last week (dev branch). It must be something related to recent changes in dsPlot then, as I originally thought...

Dave, could you take a look? You can test this easily in the cluster, please follow #260

Let me know if you should have any trouble

**Comment by kupiqu** [comment]
mmm, dsPlot didn't change either. I'm wondering what is going on here. I'll try to dig further.

**Comment by kupiqu** [comment]
Closing this as that error is not reproducible. A second run did not fail at that point. 

It is possible that there were no available centos7 nodes while runnning the cluster simulations of dsDemos, or who knows what. Anyways I will explore further if the issue somehow bites again...
