### ISSUE TITLE
netcon undefined running dsDemos both in Matlab and Octave

### ISSUE THREAD

**Issue by kupiqu** [DynaSim/DynaSim#273]
Jason, could you take a look? 

The only issue from new changes in dsDemos comes from last example. Please see below:

```
error: 'netcon' undefined near line 496 column 49
error: called from
    dsDemos at line 496 column 28
```

```
%% Delay differential equations (e.g., axonal delays in network of HH neurons)

ampa_with_delay={
  'gSYN=.1; ESYN=0; tauD=2; tauR=0.4; delay=20'
  'netcon=ones(N_pre,N_post)'
  'ISYN(X,s)=gSYN.*(s*netcon).*(X-ESYN)'
  'ds/dt=-s./tauD+((1-s)/tauR).*(1+tanh(X_pre(t-delay)/10)); s(0)=.1' % 20ms delay
  '@current += -ISYN(X_post,s)'
};

s=[];
s.populations(1).name='HH';
s.populations(1).equations='dV/dt=@current+10*(t<50);{iNa,iK};V(0)=-65';
s.connections(1).direction='HH->HH';
s.connections(1).mechanism_list='iampa';
s.connections(1).parameters={'gSYN',.1,'netcon',netcon};
s.mechanisms(1).name='iampa';
s.mechanisms(1).equations=ampa_with_delay;
data=dsSimulate(s,'time_limits',[0 100]);
figure; plot(data.time,data.HH_V);
```

**Comment by kupiqu** [comment]
This happened both locally and in the cluster

**Comment by kupiqu** [comment]
netcon, e.g., `netcon=ones(N_pre,N_post);` needs to be set in dsDemos script before be called here: `s.connections(1).parameters={'gSYN',.1,'netcon',netcon};`

**Comment by kupiqu** [comment]
commenting the line `% s.connections(1).parameters={'gSYN',.1,'netcon',netcon};` works but I'm not sure if the connectivity is properly set

**Comment by kupiqu** [comment]
This can be easily solved also by removing `'netcon',netcon` from  `s.connections(1).parameters={'gSYN',.1,'netcon',netcon};`

**Comment by jsherfey** [comment]
I removed `'netcon',netcon` in commit a5a7f9c28b571b230236ec8e8defc5e48b7ed778.

`netcon` is properly defined in `ampa_with_delay`. 

The focus of this example should be on (1) creating delay differential equations with `X_pre(t-delay)`, and (2) defining mechanisms (e.g., `iampa` via `ampa_with_delay`) in the same script as the full model specification and storing them using the `specification.mechanisms` field.
