### ISSUE TITLE
getPoissonGating bug

### ISSUE THREAD

**Issue by davestanley** [DynaSim/DynaSim#284]
Error when running getPoissonGating. This bug affects both master and dev branches as far as I can tell.

```
??? Index expression out of bounds. Attempted to access element 2. The valid range is 1-1.
More information
Error in ==> getPoissonGating Line: 52 Column: 6
Code generation failed: View Error Report
Removing failed compiled solve file: /Users/davestanley/GDrive/git/model-dnsim-kramer_IB/kramer_IB/study_d171112_t012604/solve/solve_ode_study_d171112_t012604.m
Error: 
```

The relevant lines in getPoissonGating.m are:
```
dt=T(2)-T(1);
interval=T(end)-T(1);
```

**Comment by jsherfey** [comment]
I think this is working on the latest version of the dev branch. Let me
know if it still doesn't work and I'll look into it further.

**Comment by davestanley** [comment]
Hey @jsherfey , i'm still getting the same error:

```
??? Index expression out of bounds. Attempted to access element 2. The valid
range is 1-1.
<a
href="matlab:helpview('/share/pkg/matlab/2017a/install/help/coder/helptargets.map','msginfo_Coder_builtins_IndexOutOfBounds');">More
information</a>
Error in ==> getPoissonGating Line: 52 Column: 6
            to: /projectnb/crc-nak/stanley/model-dnsim-kramer_IB/kramer_IB/study_d171206_t011211_DeltaFig8a_OnsetPoisson1/solve/sim1/solve_ode_20171206011325_541_mex

```
Again, it's the same line from `getPoissonGating.m`:
```
dt=T(2)-T(1);
interval=T(end)-T(1);
```

I'm not sure how to fix this, so I'm just going to work on an older version of dev until this gets resolved

**Comment by kupiqu** [comment]
Most likely it's not that simple, but anyways, according to the file...

`if nargin<9, T=(0:.01:1000)'; end % ms`

... T is supposed to be a column vector, did you double-check?

**Comment by kupiqu** [comment]
If that doesn't solve the issue, I guess it would help if you could show here the differences between a working version of the file (old version) and the current one (assuming the rest is the same, i.e., the calling mechanism, the main script of the model, etc.), otherwise all the differences should be showed...

**Comment by kupiqu** [comment]
Also the report by the Matlab Coder can be useful

**Comment by davestanley** [comment]
I think the issue is that Total_time (e.g. a single value telling the max time point, T(end) ) was replaced with T (e.g., an array of time values) in getPoissonGating.m.

I guess I either need to update my code to work with this, or make getPoissonGating.m backwards compatible.

Actually, I've found the exact commit that Jason made on Nov 2: a9aaf0bb52bbda19aa60dc46ea15d09c02f5ee65
"use built-in DynaSim time vector instead of constructing one from dt"

**Comment by davestanley** [comment]
In general, if we're going to make changes to core DynaSim functions that will affect not just their internal workings, but also their input-output behaviour, it would be good to inform people of these changes so they can update their code. We could use a new function name (e.g. getPoissonGating2.0.m) so that we could phase these modifications in and put a warning in the old function that it is being depreciated. This is how MATLAB does it, anyways.

@erik-roberts @asoplata, feel free to weigh in on what you think would be good procedures here.

This bug caught me right as I was finalizing my poster for SFN and the last thing I wanted to deal with at that time was hunting back through the commit history to find a working version (as I said, this bug even affected the master branch)

**Comment by kupiqu** [comment]
Yes, but there is no reason why an array cannot work, right? Once you adapt the code that calls the function, of course....

@jsherfey is there any reason why an array is preferred?

I can see one pro: an array contains the info about t_start t_end and dt, while just Total_time is limited by t_start equal 0 and dt equal to some value, which is pretty bad as dt should be consistent with dt in the solver to keep the same integration order... (of course same thing could be achieved by passing 3 arguments)

**Comment by kupiqu** [comment]
> In general, if we're going to make changes to core DynaSim functions that will affect not just their internal workings, but also their input-output behaviour, it would be good to inform people of these changes so they can update their code. We could use a new function name (e.g. getPoissonGating2.0.m) so that we could phase these modifications in and put a warning in the old function that it is being depreciated. This is how MATLAB does it, anyways.

Agreed, these changes could (and probably should) be made more gradual, but I bet most of us would ignore things until the change is finally imposed anyways. But certainly there are two responsibilities here, one by the dev and another by the user, putting us in the dev skin, this is sth we should definitely consider.

> This bug caught me right as I was finalizing my poster for SFN and the last thing I wanted to deal with at that time was hunting back through the commit history to find a working version (as I said, this bug even affected the master branch)

That was indeed very unfortunate. A lesson to be learned (putting me first as this sort of things have happened to me too): never update/pull/etc changes when running on a deadline (unless one strictly needs so, e.g., if there is a bug of some sort that was fixed).

**Comment by kupiqu** [comment]
The way I see it, the specific "bug" is solved, although it raised an important issue to discuss.

I would propose to close this specific issue and open another one about that matter...

**Comment by jsherfey** [comment]
I think I corrected this bug before submitting the manuscript. I actually
restored it to its original form.

There is now a mechanism "iPoisson" that wraps around getPoissonGating()
and is documented here:
https://github.com/DynaSim/DynaSim/wiki/Using-the-Poisson-mechanism

This is how to use it:

eqns='dV/dt=@current; {iNa,iK,iPoisson}; V(0)=-65; DC=2000; gext=.01';
data=dsSimulate(eqns,'tspan',[0 1000]);
dsPlot(data,'variable',{'V','gPoisson'});

The header for getPoissonGating has examples of using it without relying on
the mechanism, that should work in Matlab:
https://github.com/DynaSim/DynaSim/blob/master/models/getPoissonGating.m

For instance:

% % Example 1:
% baseline=1000; % Hz, baseline rate
% DC=1000; % Hz, steady component of the signal
% AC=1000; % Hz, oscillatory component of the signal
% f=10; % Hz, modulation frequency of the signal
% phi=pi; % radians, phase at which the signal begins
% onset=200; % ms, start time of signal
% offset=800; % ms, stop time of signal
% tau=2; % ms, synaptic time constant
% time=0:.01:1e3; % ms, time vector
% Npop=2; % size of target population
% s=getPoissonGating(baseline,DC,AC,f,phi,onset,offset,tau,time,Npop);
% dsPlot(s,'plot_type','waveform');
% dsPlot(s,'plot_type','power');

Do these examples work for you?

**Comment by davestanley** [comment]
Ok thanks @jsherfey  I'll give this a try

**Comment by DynaSim** [comment]
This example shows how to use getPoissonGating() to create an AMPAergic
synaptic input:

% eqns={'dV/dt=@current+Iampa(V); {iNa,iK}; monitor Iampa';
% 'Iampa(V)=-gext*s(k,:).*(V-0); s=getPoissonGating(0,DC,AC,f)';
% 'gext=.001; DC=25000; AC=25000; f=5; V(0)=-65'};
% data=dsSimulate(eqns,'tspan',[0 1000]);
% dsPlot(data,'variable',{'V','Iampa'});

**Comment by davestanley** [comment]
Thanks I figured out how to use it. It was pretty straight forward

The problem was more with the fact that I was trying to debug other things at the same time and was not expecting the underlying code base to change.

If we are going to change how the function definitions work for front-end user-accessible functions, I think it would be good to fade these changes in gradually. This is especially the case when we're pushing these changes to master

**Comment by davestanley** [comment]
I'll close this issue but perhaps we can discuss the procedure for this at the next meeting

**Comment by jsherfey** [comment]
I agree. I think the bug arose in the first place because the front-end
user-accessible function was changed by someone without discussing it and
without there being a procedure in place.

**Comment by erik-roberts** [comment]
> In general, if we're going to make changes to core DynaSim functions that will affect not just their internal workings, but also their input-output behaviour, it would be good to inform people of these changes so they can update their code. We could use a new function name (e.g. getPoissonGating2.0.m) so that we could phase these modifications in and put a warning in the old function that it is being depreciated. This is how MATLAB does it, anyways.
> 
> @erik-roberts @asoplata, feel free to weigh in on what you think would be good procedures here.
> 
> This bug caught me right as I was finalizing my poster for SFN and the last thing I wanted to deal with at that time was hunting back through the commit history to find a working version (as I said, this bug even affected the master branch)

ideally the default IO would not change. but if a change is done, it should not affect default behavior and thus be backward compatible. to do this one could use varargin and check inputs or  tack on a final flag for using the new version, and then phase out the default behavior after a committee review.

**Comment by kupiqu** [comment]
In general yes, but in this particular case, I think the old behavior was buggy. If I'm not wrong, it utilized a fixed dt which caused two potential problems:

- a mild problem: dt in the function is not associated to dt of the solver, so the integration order is messed up

- an important problem: also the Poisson realization won't be consistent because of the distinct dt, events will appear in the solver happening earlier or later, if, as I think it's hapenning, each Poisson current timestep is read out by the solver file by a natural index...
