### ISSUE TITLE
Compiler vs Coder

### ISSUE THREAD

**Issue by kupiqu** [DynaSim/DynaSim#288]
We should use the proper terms within DynaSim and between us. What we have in DynaSim is a call to MATLAB's coder, NOT compiler. I know the labels chosen by MATLAB are arbitrary, but we should try to avoid the confusion:

https://stackoverflow.com/questions/18126407/matlab-compiler-vs-matlab-coder

**Comment by erik-roberts** [comment]
good point. is this fixed in the paper?

**Comment by kupiqu** [comment]
I think it would be quite more appropriate to change compiler_flag to coder_flag, in DynaSim, Documentation, Manuscript, etc etc... can somebody carefully go through this...?

**Comment by kupiqu** [comment]
Please see #356
