### ISSUE TITLE
use subplot_grid instead of tight_subplot

### ISSUE THREAD

**Issue by jsherfey** [DynaSim/DynaSim#29]
http://www.mathworks.com/matlabcentral/fileexchange/34191-subplot-grid

**Comment by davestanley** [comment]
Nice suggestion

I've been working on this and converted PlotFR over to use subplot_grid (along with some other modifications).

I might tackle PlotData if I have time, but if someone else does this please do share.

**Comment by erikthered12** [comment]
i had some issues with spg. ill try to recall what they were

**Comment by jsherfey** [comment]
This has been resolved in dsPlot2(). 

https://github.com/DynaSim/DynaSim/blob/master/functions/dsPlot2.m
