### ISSUE TITLE
parallel mode instability on the cluster

### ISSUE THREAD

**Issue by davestanley** [DynaSim/DynaSim#301]
I recently submit the following ticket to the BU SCC help:

I’ve been opening multicore interactive session (e.g. using the command qlogin -l h_rt=2:00:00 -pe omp 8 ). However, when I run my code, I get the following error. This does’t happen on every run, but rather seems to occur at random on about 50% of my runs. I’m having difficulty debugging it and am not sure if it’s a problem with my code, with Matlab, or with my processes being killed - can you perhaps advise?

I haven’t received any emails from root about my processes being killed.

The error is as follows:

`The client lost connection to worker 8. This might be due to network problems, or the interactive communicating job might have errored.
`

The simulation then terminates

So far this has made parallel mode on the cluster almost unusable. It still runs fine on my local machine. I'll let you know if I find a solution to this.

**Comment by erik-roberts** [comment]
any updates from BU SCC help?

**Comment by erik-roberts** [comment]
also, are you getting this bug:  #344
