### ISSUE TITLE
Add ability to specify # of spikes in buffer

### ISSUE THREAD

**Issue by jsherfey** [DynaSim/DynaSim#304]
e.g.) V.spikes(thresh,buffer_size)

**Comment by jsherfey** [comment]
Issue mostly resolved in Pull Request #336

      % Supported:
      % - monitor VAR.spikes(#)
      % - monitor VAR.spikes(thresh)
      % - monitor VAR.spikes(thresh,#)
      % - monitor VAR.spikes(#,#)

      TODO: support: monitor VAR.spikes(thresh,buffer_size)

**Comment by erik-roberts** [comment]
@jsherfey what does monitor VAR.spikes(#,#) do?
