### ISSUE TITLE
Improve the use of diff in dsCompareSolveFiles.m

### ISSUE THREAD

**Issue by kupiqu** [DynaSim/DynaSim#307]
We don't want diff to be targeted to SCC, and given the importance of the command for the behavior of DynaSim, I will work to improve it in the following way:

- Check which arguments are the best to pass to diff so it discriminates models optimally irrespective of meaningless differences (empty lines, tabs, whitespaces)
- ~If the best set of arguments is not supported by diff in SCC, check whether there are different versions of diff in module~ There are no different versions of diff in SCC, but it seems the optimal set of arguments is supported (see comment below)
- In any case, save the error code of matlab's system call, so if something fails a more robust diff command can be applied
- More generally, save the diff output from matlab's system call (if not empty) to a file for easier checking of the differences between models or diff errors

**Comment by kupiqu** [comment]
In dummy surrogated text files, it seems `diff -aBEw` works best and equally fine in my system and in SCC

```
       -a, --text
              treat all files as text
       -B, --ignore-blank-lines
              ignore changes whose lines are all blank
       -E, --ignore-tab-expansion
              ignore changes due to tab expansion
       -w, --ignore-all-space
              ignore all white space
```

I have to double check if it is just fine to remove all whitespaces of solver files. I guess so but better to check it out to avoid surprises...

**Comment by erik-roberts** [comment]
nice work!

**Comment by kupiqu** [comment]
The only 'issue' that I foresee is if a solver file contains a explicit string with whitespaces or tabs (some sort of a label or sth). Then that string could be different in two distinct models (and be meaningful?) and the above diff command would fail to distinguish among them.

But I think this can never be a use case, can it @jsherfey?

**Comment by erik-roberts** [comment]
if that were an issue, is that an option to ignore trailing whitespace?

**Comment by kupiqu** [comment]
Done in commit ce45c42b24c09b57f2773f28ae91c2739755c90a

```
% -B neglects empty lines, -b neglects in-between (>1) and trailing (all) whitespace, sed with regexp is used to neglect leading whitespace
 [status,diffs] = system(['diff -Bb <(sed ''s/^[ \t]*//'' ' solve_file_m ') <(sed ''s/^[ \t]*//'' ' fullfile(mexPath,files{f}) ')']);
```

I think it's fine but if you think having a diff file, whenever a mex file is created, is too verbose, we could only save it while in debug mode.

Thinking about it, perhaps I should have named the diff file as the solver file... I will add the change and then will close this issue...

**Comment by kupiqu** [comment]
@jsherfey I did this change and now dsDemos creates a bunch of diff files that shouldn't be present...

Why is that? why is dsCompareSolveFiles called when the coder is disabled? 

Isn't it weird? Is this a bug?

**Comment by kupiqu** [comment]
I don't want to merge the change until this is figured out... :/

**Comment by kupiqu** [comment]
I figured out why... using status and verbose_flag to get rid of diffs

**Comment by kupiqu** [comment]
Ok, done with merge 5023e5ea555dac96998ab1f51e3f1bfe910758f1

Unfortunately the status variable returned by the system call is not reliable to distinguish errors from regular output, so I just used the verbose flag to either keep or not diff files.
