### ISSUE TITLE
Add the whole list of DynaSim flags in a section of the wiki

### ISSUE THREAD

**Issue by kupiqu** [DynaSim/DynaSim#314]
I was thinking, do we have a debug flag in DynaSim? And then checked the wiki to see if there were a list of flags, I couldn't find it, and I think it should be...

So, is it a debug flag? I still don't know... if not, I think we should create it, so it generates ouput that can be useful to see what is going on when things go wrong... (e.g., I would use it instead of the verbose flag to keep diff files in dsCompareSolveFiles.m as this is sth we may be interested in looking at when sth fails). I'll wait to open an issue about the debug flag until I got an answer to whether it is already there...

**Comment by erik-roberts** [comment]
good idea.

and yes there is a debug flag that removes the `try` statement so that `dbstop if error` actually works for debugging. however, it doesn't print additional info.

**Comment by kupiqu** [comment]
Well,unless you have the function references embedded in the documentation somehow, it's kind of a weird documentation that you need to go to the function code to know about sth (that important).

Sure there may be diffs between master/debug/ and dev, but I think recommended versions for final users should be:

- released stable versions (we don't have any)
- master version, otherwise

and intended documentation for users should be linked to those

Only risky users, testers and devs should be using debug, dev and other branches, ideally with specific documentation associated with each.

The best thing to manage this would be to have a way (if it's not there already) to embed all function references into the documentation, so it's automatically generated and then, as you said, we can refer users to check things to that, e.g., available DynaSim flags -> dsSimulate function reference in documentation (ideally with a link in the wiki, or so).

**Comment by erik-roberts** [comment]
great idea! i'll add the links.

**Comment by erik-roberts** [comment]
https://github.com/DynaSim/DynaSim/wiki/Option-reference
