### ISSUE TITLE
Exist on matlab path vs. Exist in directory

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#32]
There's an issue with how exist is sometimes used in the code, for example in setupStudy, in which it checks if a directory exists using isdir or exist(name,'dir'). The problem is that in those cases, it needs to check if the directory exists in the given/current directory, not somewhere else in the path, but isdir and exist do the latter, not the required former. This needs to be refactored to check existence using the ls or dir functions.

**Comment by davestanley** [comment]
Came across this issue in SetupStudy. Fixed by changing
if isdir(options.study_dir)
to
if ~isdir(fullfile('.',options.study_dir))

Commit d572d7047f483923d4ef56aef3a6dcc710fe0935 fixes this

**Comment by erikthered12** [comment]
duplicated in #103
