### ISSUE TITLE
Text error in PlotData on Matlab 2014b, running on server

### ISSUE THREAD

**Issue by davestanley** [DynaSim/DynaSim#34]
The error I got was with the text command on line 694 of PlotData:  'First two or three arguments must be numeric doubles'

I fixed this by adding the line:
text_xpos=double(text_xpos);

Before the line:
text(text_xpos,text_ypos,text_string{row,col},'FontSize',20);

This is line 691 in PlotData.

However, it seems I do not have permissions to push these changes.

**Comment by jsherfey** [comment]
This has been resolved.
