### ISSUE TITLE
Change 'parallel_flag' to 'multicore_flag'

### ISSUE THREAD

**Issue by asoplata** [DynaSim/DynaSim#343]
Right now, `parallel_flag` runs multicore simulations, which is parallel computing, but `cluster_flag` runs embarrassingly parallel batch jobs on a cluster, *which is also technically parallel computing* (see https://en.wikipedia.org/wiki/Parallel_computing#Classes_of_parallel_computers ). If we change `parallel_flag` to be something more specific like `multicore_flag`, then I think that will make it less confusing for newcomers, since `parallel_flag` sounds like the main flag used for parallelization -- which is not correct, since there are multiple methods for parallelization in DynaSim.

**Comment by kupiqu** [comment]
We decided to go for `parfor_flag`

Done with pull requests #351-#354
