### ISSUE TITLE
dsAnalyze error related to #396

### ISSUE THREAD

**Issue by davestanley** [DynaSim/DynaSim#397]
There is also an issue with the line 

```
    if isempty(result)
      error('result empty.')
    end
```
Specifically, dsPlot sometimes does not exhibit a return value. For example, when specifying the 'plot_type' as 'power', the handles return value is empty (don't ask me why it behaves this way).

However, this produces an error. For example, running the code:

```
  % Save multiple plots and pass custom options to each plotting function
  eqns='dv/dt=@current+10; {iNa,iK}';
  dsSimulate(eqns, 'save_data_flag',0, 'study_dir','demo_cluster_3','save_results_flag',1,...
                     'overwrite_flag',1, 'verbose_flag',1,...
                     'plot_functions',{@dsPlot,@dsPlot},...
                     'plot_options',{{},{'plot_type','power'}});           
```

Yields

```
Error using dsAnalyze (line 358)
result empty.
Error in dsSimulate/tryFn (line 1111)
            tmpresult = dsAnalyze(tmpdata, siminfo.result_functions{f},'result_file',siminfo.result_files{f},'save_data_flag',1,'save_results_flag',1, siminfo.result_options{f}{:},
            'parfor_flag',dsAnalyze_parfor_flag, 'in_sim_flag',1);
Error in dsSimulate (line 805)
    tryFn(nargout) 
>> 
```

**Comment by davestanley** [comment]
Ok, I've figured out what is causing this. An error with dsPlot (see iss #398) was causing dsPlot to error when producing the power plot.

Because of the try-catch clause in dsSimulate, this would not produce an error. Instead, the function would close without providing a return value, which triggered this error further downstream.

@erik-roberts  If we're going to use this new try-catch clause, can we have some way of notifying the user when errors do happen (even if the code continues to run)? 

Having these unreported errors makes debugging very difficult!

**Comment by erik-roberts** [comment]
i'm not able to reproduce this error on my local computer. is it still happening? what system are you using?

i removed the try-catch because i don't think it's necessary. hopefully that will make debugging easier.
