### ISSUE TITLE
PlotData's "Power" analysis seemingly incorrect

### ISSUE THREAD

**Issue by asoplata** [DynaSim/DynaSim#40]
Sigh. I've been helping Wei Zhong (current Kopell rotation student) get situated with DynaSim, and have discovered a very interesting case where PlotData's spectral analysis is NOT giving what I think it should. Forewarning: I could just be misinterpreting the effectiveness of general spectral analysis to work on a particular class of spike trains, but I don't think that's the case.

Below are the voltage traces from a four-cell model, with one of each type (thalamic TC and RE cells, and cortical PY and LTS cells). These celltypes are from ShiNung's paper (Ching 2010 https://www.ncbi.nlm.nih.gov/pubmed/21149695), and I can give you the mechanism files if you want. Note: there is NOTHING wrong with the voltage traces, they look exactly like they're supposed to look, resembling Figure 4 of that paper

![study_sim1_plot1_plotdata](https://cloud.githubusercontent.com/assets/661173/20846121/182dfc54-b896-11e6-867c-3fcc919300c9.png)

However, when I run this data through PlotData's power analysis, for example via `PlotData(data,'plot_type','power')`, I get this 
![study_sim1_plot2_plotdata](https://cloud.githubusercontent.com/assets/661173/20846237/ba9f8c78-b896-11e6-8395-e337e42f79ff.png)

Which is VERY surprising to me when it comes to the PY cell's especially. Unless I'm severely misinterpreting something, I would expect VERY strong power from either the spikes or at LEAST the membrane potential's very periodic behavior to show up on the spectrogram. I almost have a hard time believing that the TC cell's power is stronger than the PY cell's, when the PY is so regular. This says to me that, best case scenario, PlotData's power analysis just isn't effective in analyzing certain kinds of spiking patterns, and at worst wrong. What is going on????????????????

**Comment by erikthered12** [comment]
the top 2 have stronger sub threshold oscillations than the bottom two. the spectrum looks like the spectrum for the time series without spikes. the spikes should have power at all frequencies, but perhaps most of the power is concentrated at high frequencies so you don't see it under 40 hz here.

in general spectrum power doesn't seem best to describe this kind of data.  for one, point process power isn't interpreted in the normal way. the autocorrelation of the spike times for a measure of spiking rhythmicity or the spectrum of the spike subtracted data for sub threshold oscillations makes the most sense to me. what do other people think?

**Comment by asoplata** [comment]
The only excitatory drive to the TC cell is coming from the PY cell. So if it's predominantly detecting subthreshold oscillations, shouldn't the PY's very consistent rises from -100 mV to -60 show up MORE than the TC cell's in the spectrum?

Also, I looked at much higher frequencies of the power spectrum (up to 200 Hz), but I only saw weaker harmonics from the small bump at 16-17 Hz.

I agree that this isn't the best way to describe the data...but I find it worrying that there is such a HUGE spectral difference between the TC and PY cells here, when IMHO the PY's spectral peak should be of greater magnitude. Anyone else???

**Comment by benpolletta** [comment]
Hey guys,

Austin, remember that the measure of spectral power in a Fourier transform
is how well a time series matches a sinusoidal basis function of a given
frequency. The thalamic cells are (both) much more sinusoidal. The
pyramidal cell traces may be periodic, but they aren't sinusoidal - and the
less sinusoidal a function is, the more its variation is spread across
frequencies in a Fourier transform.

If you're interested in variability (i.e. the depth of changes in membrane
voltage), you can use something like a standard deviation.

If you're interested in periodicity, you'll need a different measure -
something like a Poincare map is what comes to mind.

And, as Erik points out, if you're interested in the periodicity of
spiking, you'll have to isolate the spikes from the subtheshold
oscillations. Simply making a zero-one time series with a one at the time
of each spike, and then performing spectral analysis of this time series,
will give you what you're looking for. Whether and how much spikes affect
the spectral content of a voltage trace probably depends on lots of things,
including the shape of the spike and its width, and the subthreshold
dynamics associated with each spike. But if you separate the spikes, you
can be sure that's all you're looking at.

Of note, in LFP/EEG data, spikes don't appear with much magnitude.
Similarly, averaging across units in modeling data can remove the spectral
structure (or lack of it) in spikes from a voltage time series. In averaged
traces, subthreshold oscillations show up clearly (if they are time-locked
across stimulations), and bursts or population spike volleys both show up
as moderate low frequency variations (again conditional on whether they're
time-locked).

Anyway, that's all the input I have for now.

B

**Comment by kupiqu** [comment]
Edit: Ben commented while I was writing, I think both of us kind of agree on the main issue here...

Mmm, I don't use DynaSim for data analysis, so I don't know what sort of spectral analysis is this. I guess it's based on FFT, but still, does it use tapers? If so, what are the parameters of it, etc etc.

Second, I typically do spectral analysis of spikes or lfps (surrogated from synaptic inputs). Mixing spikes and subthreshold oscillations may be tricky. And if working on spikes is always good to do in the same time interval as here, with the same number of cells as here, and controlling for the firing rate, which is not the case here.

However, I guess what is mainly going on here is that spikes are huge variations of voltage but they happen on very narrow window times, so the effect of subthreshold oscillations is still much larger (even though delta_V is smaller) as they resemble much better sinusoidal waves, which is what the typical power spectrum is about.

**Comment by asoplata** [comment]
Thanks for all the comments everyone! I especially didn't realize that the FFT
response depended that much on the waveform of underlying oscillations, that's a
little mind blowing. I always assumed that, since you can reconstruct the signal
perfectly from its Fourier'd content, the FFT's spectral analysis would always
reveal all non-sinusoidal, periodic content too. All these comments make for a
lot to chew on...I think I will revisit some textbooks. Thanks a bunch! Erik was
explaining some specific pitfalls to me the other day, and if people are
interested, maybe it would be a good idea to 1. have a session going over
pitfalls of analyzing our overly clean modeling data (if people want), and 2. in
lieu of a similar email from Erik, maybe we could write more code integrated
into DynaSim's `PlotData` that does more spike analysis (like ISIs).

On Fri, Dec 02, 2016 at 12:40:54PM -0800, kupiqu wrote:
> Edit: Ben commented while I was writing, I think both of us kind of agree on the main issue here...
> 
> Mmm, I don't use DynaSim for data analysis, so I don't know what sort of spectral analysis is this. I guess it's based on FFT, but still, does it use tapers? If so, what are the parameters of it, etc etc.
> 
> Second, I typically do spectral analysis of spikes or lfps (surrogated from synaptic inputs). Mixing spikes and subthreshold oscillations may be tricky. And if working on spikes is always good to do in the same time interval as here, with the same number of cells as here, and controlling for the firing rate, which is not the case here.
> 
> However, I guess what is mainly going on here is that spikes are huge variations of voltage but they happen on very narrow window times, so the effect of subthreshold oscillations is still much larger (even though delta_V is smaller) as they resemble much better sinusoidal waves, which is what the typical power spectrum is about.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/DynaSim/DynaSim/issues/40#issuecomment-264557211

-- 

Austin E Soplata,
Graduate Program for Neuroscience,
Boston University
L | www.linkedin.com/in/austinsoplata
P | +1 901 486 9833
T | @austinsoplata
