### ISSUE TITLE
cannot change initial conditions from vary or spec param

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#432]
problem:
only `dsParseModelEquations` changes IC
thus only equations can modify IC, like with lorenz demo
this is called by dsCheckModel > dsGenerateModel > dsImportModel > dsParseModelEquations

cannot change initial conditions using a vary statement (this would require IC check in `dsApplyModifications`, which isn't there)
or the model specification.parameters (in dsImportModel for parameters)

solution:
add IC change to `dsApplyModifications` from vary
add IC change to `dsImportModel` from params in subfn `set_user_parameters`
use `dsParseModelEquations` as starting point

**Comment by erik-roberts** [comment]
@asoplata this is a problem

**Comment by erik-roberts** [comment]
@jsherfey do you know if there is a reason this isn't there?

**Comment by jsherfey** [comment]
It should work with parameterized initial conditions. e.g.,

Given:
V(0)=ic+r*randn(1,Npop);

You can vary the IC using:
vary={'pop1','ic',[-75 -65 -55]; 'pop1','r',[0 5 10]};

And you can set the IC using spec param like:
s.populations(1).parameters={'ic',-65,'r',10};

Does this not work or are you referring to doing something else?

**Comment by erik-roberts** [comment]
already working now:
`equations`
`s.populations(1).equations`

**Comment by erik-roberts** [comment]
fixed in iss432_init_cond

**Comment by erik-roberts** [comment]
remaining bug:
will have too many ICs

**Comment by erik-roberts** [comment]
fixed for param

**Comment by erik-roberts** [comment]
bug:
when set in vary, it overwrites state variable vector in data. makes separate TC_V and TC_0 that both are scalar with the varied TC_V(0)

**Comment by erik-roberts** [comment]
bug:
doesnt work with vary for cluster sims
uncertain about spec.param for cluster sims

solution:
?
