### ISSUE TITLE
<dev> Naming conventions for data.model.specification.populations

### ISSUE THREAD

**Issue by davestanley** [DynaSim/DynaSim#455]
I am having an issue plotting some data saved from a previous run. Specifically, dsPlotFR is looking for a a field called `mechanisms,` which is not present. Did anyone change the names of the variables mechanisms and mechanism_list under?

Note that I am loading some data that I saved earlier using dsImport. 

The specific location `dsPlotFR` is looking is:
`data(1).model.specification.populations`

To reproduce this error, I am running the dsPlot2 tutorial code (dsDemos_PlotData2.m).

```
%% Set up paths 
% Get ready...

% Add DynaSim to path if it's not already there
if exist('setupDynaSimPath','file')
    setupDynaSimPath;
else
    error('Add the DynaSim folder to the MATLAB path - e.g. run addpath(genpath(DynaSimPath))');
end

% Set where to save outputs
output_directory = dsGetConfig('demos_path');
study_dir = fullfile(output_directory,'demo_sPING_100cells_3x3');

%% Import the data

% Make sure sample data exists; if not copy it into place
if ~exist(study_dir,'dir')
    dsUnzipDemoData(study_dir);
end

% Load data in traditional DynaSim format
data=dsImport(study_dir);
```

And then

`dsPlotFR(data)`

The full error is:

```
Reference to non-existent field 'mechanisms'.
Error in dsGetNamespaces (line 24)
  for j=1:length(spec.populations(i).mechanisms)
Error in dsGetParentNamespace (line 11)
namespaces=dsGetNamespaces(model);
Error in dsSelectVariables (line 53)
  parent=dsGetParentNamespace(data(1).model,data(1).labels{1});
Error in dsCalcFR (line 123)
options.variable=dsSelectVariables(data(1),options.variable, varargin{:});
Error in dsAnalyzeStudy (line 65)
    results(i)=feval(func{j},data(i),varargin{:});
Error in dsCalcFR (line 73)
  data=dsAnalyzeStudy(data,@dsCalcFR,varargin{:});
Error in dsPlotFR (line 46)
  data=dsCalcFR(data,varargin{:}); % equivalent: data=dsAnalyzeStudy(data,@dsCalcFR); 
>> 
```

Again, this is on <dev>. Any insight would be great. If I get a chance, I'll just regenerate this data, but I'd rather not if can be avoided.

**Comment by erik-roberts** [comment]
which line in dsPlotFR? I'm not finding it.

**Comment by erik-roberts** [comment]
I feel like Jason brought this up at one point awhile ago in one of our meetings. i can't find it documented in the minutes or in the issues.

**Comment by erik-roberts** [comment]
It appears that there is a `specification.mechanisms` field as well as a `specification.populations/connections.mechanisms` and `specification.populations/connections.mechanism_list` field. The mechanisms fields are structures with `name` and `equations` fields. the `mechanism_list` field is a cell array of paths to the mechanism files.

**Comment by erik-roberts** [comment]
Also, i get this error:
```
Downloading file from: https://github.com/DynaSim/DynaSimFiles/blob/master/demos/demo_zips/demo_sPING_100cells_3x3.zip?raw=true ... Error using dsDownloadFiles (line 72)
Requested file not found!

Error in dsUnzipDemoData (line 53)
        dsDownloadFiles(fullfile(demo_zips_path,zipfname));
```

**Comment by erik-roberts** [comment]
if you want to avoid resimulating, you could add to the spec with something like:
`dsCheckSpecification(studyinfo.base_model.specification)`

**Comment by davestanley** [comment]
Ok, I just re-ran the simulation and uploaded it to the DynaSimFiles, so we should be good. Closing the issue, since it's a backwards compatibility issue.
