### ISSUE TITLE
Add more plotting to dsPlot

### ISSUE THREAD

**Issue by asoplata** [DynaSim/DynaSim#462]
I'd like to add some more "plot_type"s to dsPlot, since they would be useful for my research (and hopefully others'). Specifically, I'd like to add

- [x] waveform_averaged
- [x] MUA_only_flag to `dsCalcPower` and `dsPlot` [commit 3706b85](https://github.com/asoplata/DynaSim/commit/3706b85a33c645c3a0215575be53ef1583c775dc)
- [ ] spectrogram_averaged
- [ ] modulation_index_averaged (which wraps dsCalcModulationIndex so the user can choose their bands/filters)
- [ ] (optional) comodulogram_averaged
- [ ] (optional) waveletogram_averaged

Object now, or forever hold your peace.

**Comment by asoplata** [comment]
After discussion in #279 , changing names to

- waveform_averaged
- spectrogram_averaged
- modulation_index_averaged
- comodulogram_averaged

**Comment by erik-roberts** [comment]
I've seen waveform averages get triggered by default when multiple variables are plotted for multiple cells. @asoplata were you able to reuse that code?

**Comment by erik-roberts** [comment]
What are you planning to use to implement MUA_spectrogram?

**Comment by asoplata** [comment]
I'm dumb and this is a duplicate of #424 which Dave has already mostly implemented. Closing.

**Comment by davestanley** [comment]
Averaging is implemented in dsPlot2, but not the other options
