### ISSUE TITLE
Add control of Matlab version on cluster (and decide on new default version?)

### ISSUE THREAD

**Issue by asoplata** [DynaSim/DynaSim#465]
Given that the default Matlab version on the cluster is 2013a ([see here](http://www.bu.edu/tech/support/research/software-and-programming/common-languages/matlab/)) and the fact that this version is old enough to begin causing problems (see #398 and #429), **we should add an easy way to change the Matlab version used in batch simulations on the cluster**, and, for the purposes of batch simulations, consider changing the "default" Matlab version loaded.

This should be as easy as changing `dsCreateBatch` and `dsAnalyze` to use 

```{matlab}
ui_command = strcat('module load matlab/', options.matlab_cluster_version, ' ; matlab -nodisplay -nosplash -singleCompThread -r');
```
instead of 
```{matlab}
ui_command = 'matlab -nodisplay -nosplash -singleCompThread -r';
```

Finally, this is also relevant to #306 and should make it considerably easier.

**Comment by asoplata** [comment]
#467 is also a byproduct of using this outdated Matlab version.

**Comment by erik-roberts** [comment]
this is buggy.

**Comment by erik-roberts** [comment]
also, the scc people said we sometimes need to do this:
`module load mcr/9.3_2017b`

**Comment by erik-roberts** [comment]
bug with dsAnalyze. arguments aren't processed correctly now.  need 2 single quotes around the new shell argument.

**Comment by jsherfey** [comment]
The paper says we support 2013a-2017b. My vote is to make the default close
to the lower bound on the versions we support. That way we are less likely
to write code that relies on functions added after 2013a. 2014a seems to
work well on the cluster for me. How about that?

**Comment by erik-roberts** [comment]
dsSImulate to 2014a (5f138be). dsAnalyze was moved to 2014a in earlier commit.
