### ISSUE TITLE
Parallel mode unavailable on cluster Matlab version 2013a (dev branch)

### ISSUE THREAD

**Issue by asoplata** [DynaSim/DynaSim#467]
`dev` branch parallel on the cluster uses the function `parpool`. However, the default Matlab version on the cluster is 2013a, and `parpool` was not introduced until 2013b. The quick and dirty fix is that someone can set `cluster_matlab_version` to 2013b or later (see 68950e0). However, this will not solve the problem for new users, and there are other issues arising from using such an old version of Matlab, e.g. #429. I believe the best permanent solution, is deciding upon a new, targeted Matlab version -- see #465.

(Note: this is distinct from #301 and #344 )

**Comment by erik-roberts** [comment]
closing since switched default to 2014a.
