### ISSUE TITLE
Multiple synaptic linkers not working

### ISSUE THREAD

**Issue by asoplata** [DynaSim/DynaSim#477]
When attempting to use a synaptic mechanism containing multiple linkers, like:

```
@current += -IAMPAHB(X_post,w,s)
@ihb += IAMPAHB(X_post,w,s)
```

the linkers are not always replaced with the contents they are supposed to be replaced with. This is in part due to a small bug in [Line 347 of `dsGenerateModel.m`](https://github.com/DynaSim/DynaSim/blob/dev/functions/internal/dsGenerateModel.m#L347). There is an additional unknown bug preventing linker replacement in the monitors of functions contained such a linker.

**Comment by asoplata** [comment]
See https://github.com/asoplata/DynaSim/tree/iss477_syn_linkers for progress

**Comment by erik-roberts** [comment]
> Line 347 of dsGenerateModel.m.

note: line # has changed now

**Comment by kupiqu** [comment]
I think this issue is fixed now. @asoplata please reopen if you still can reproduce the issue
