### ISSUE TITLE
compilation fails when code is contained in a folder with a space in the name

### ISSUE THREAD

**Issue by sg-s** [DynaSim/DynaSim#479]
the error is in this file: 

```
Error in dsPrepareMEX>makeMex (line 112)
  eval(['codegen -d codemex -config cfg ',file]);
```

`file` is not sanitized, and it is assumed that there is no space in it.

**Comment by erik-roberts** [comment]
fix to implement:
eval(sprintf('codegen -d codemex -config cfg "%s"', file));

**Comment by erik-roberts** [comment]
@sg-s this should be working now on dev branch.

**Comment by sg-s** [comment]
thanks!
