### ISSUE TITLE
modifications in data

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#49]
studyinfo.simulations.modifcations should be in data, since there is no way to know from a data file what was modified without looking back at studyinfo

**Comment by jsherfey** [comment]
data(i).varied includes a list of what was varied. The value for varied element j in simulation i is stored in data(i).(varied{j}) where varied=data(i).varied.

**Comment by erik-roberts** [comment]
@jsherfey what about setting the parameters with s.populations.parameters? Will that or the base model be stored in the data file and study info?

**Comment by jsherfey** [comment]
studyinfo (which stores metadata for a study/batch) stores the base model
and a list of simulation-specific modifications.

The data file and structure (for a single simulation) stores whatever
specification/model (including parameters) was used to generate it in
data.model and data.model.specification.

I'm not sure what you mean by setting parameters with
s.populations.parameters?

**Comment by erik-roberts** [comment]
I'm referring to overriding parameters with `s.populations.parameters` vs. the initial parameters inside of `s.populations.mechanisms` files
