### ISSUE TITLE
checking for Nans

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#50]
often my sims give Nans if my timestep is too large. it would be nice to have a warning about this, especially during a local batch.  even better, it would be nice to have an adaptive timeStep that shrinks if it gets nans.

**Comment by erikthered12** [comment]
use while loop and use smaller time step with larger downsample factor

**Comment by jsherfey** [comment]
adaptive time steps can be used by setting 'solver' in dsSimulate to a built-in Matlab ODE solver {'ode23','ode45','ode113','ode15s','ode23s','ode23t','ode23tb'}. This was made possible by creating dsWriteMatlabSolver().

**Comment by erik-roberts** [comment]
however, the adaptive time step functions don't work well for many of our neuro models. Setting `MaxStep` using `odeset` doesn't solve this problem.

**Comment by erik-roberts** [comment]
ill move this to #274
