### ISSUE TITLE
Changes to plotting - conductance plots inverted

### ISSUE THREAD

**Issue by davestanley** [DynaSim/DynaSim#529]
I noticed that some of my conductance plots are inverted with the latest pull of DynaSim dev.  Did anyone change how conductances or current monitors are saved?

Here's how it looks now (note the blue traces):
![image](https://user-images.githubusercontent.com/5439305/45532271-738d2080-b7c1-11e8-8f82-67cfdf182b92.png)

Here's how they should look (red trace - it's the inverse of the previous)
![image](https://user-images.githubusercontent.com/5439305/45532288-80aa0f80-b7c1-11e8-83ea-1e38e4426784.png)

**Comment by erik-roberts** [comment]
what command did you use?

**Comment by davestanley** [comment]
This is all with dsPlot2. However, it's my own custom function handle is being passed, that in turn calls dsPlot's rastergram function

Also, I noticed the colour of the ticks changed from black to blue - is there a way to control the color in the new rastergram code? (I'm away from Matlab right now, but can probably look this up myself)

**Comment by davestanley** [comment]
Ok, I'll do this. Right now all the other figures in my paper so far are using black ticks, so it would be confusing to start using blue ticks all of a sudden

**Comment by davestanley** [comment]
I've removed the y-axis inversion with commit 6653b0739e0dbad2471891a92c8fd90e33ef0c0e and am closing this issue for now.

Note that this will have the effect of flipping all rastergram plots, so the first population will no longer be on top. If this creates problems for some people, feel free to re-open and ping me so we can discuss the best convention here. Ideally, we should have the first pop on top _without_ requiring the axis to be inverted.
