### ISSUE TITLE
Mechanism File Priority

### ISSUE THREAD

**Issue by benpolletta** [DynaSim/DynaSim#53]
If you have two mechanism files with the same name in different directories (say, in the working directory and another), which one is used in the current model?

**Comment by benpolletta** [comment]
Similarly, given that multiple filename extensions for mechanisms are supported - I have seen '.txt' and '.mech' - if you have two identically-named mechanisms with different extensions, which is prioritized?

**Comment by jsherfey** [comment]
Re: two files with same name in different directories:
dsLocateModelFiles() searches the current working directory and then your Matlab or Octave path. The file in the current working directory (if one exists) is prioritized first; then files in directories earlier in the Matlab or Octave path will be prioritized over files in directories appearing later.

Re: X.mech vs X.txt:
'.mech' should always be used; it is prioritized over '.txt'.

**Comment by erik-roberts** [comment]
adding to wiki
