### ISSUE TITLE
Compatibility Between Linkers and Model Equations

### ISSUE THREAD

**Issue by benpolletta** [DynaSim/DynaSim#54]
PROBLEM: There seem to be two linker types supported in DynaSim:

@current += I_mech
current => I_mech

There seem to be issues using mechanisms with different linker types in the same model. This seems to be related to how the equation is written for each model, one of:

V' = @current/Cm
V' = current/Cm

SOLUTION: It would be very nice to have a way to correct the linker type for a given equation. This might involve tampering with the core code that writes the model by string manipulation; alternatively, it could be a check performed before or after the model is written, correcting the linker for each mechanism (by string replacement) to make sure they are compatible with the model equations.

**Comment by jsherfey** [comment]
@current is the recommended linker type. All references to "current" as a linker name have been removed (although they are still supported).

**Comment by erik-roberts** [comment]
it might be good to check for floating linkers.

**Comment by DynaSim** [comment]
What are "floating linkers"?

**Comment by erik-roberts** [comment]
> it might be good to check for floating linkers.
> What are "floating linkers"?
I guess they could be called unlinked linkers as i'm arguing should be checked for in #296
