### ISSUE TITLE
Dimension mismatch error in .mech file not producing error in DynaSim

### ISSUE THREAD

**Issue by davestanley** [DynaSim/DynaSim#550]
I discovered a dimension mismatch error in one of my synapse mech files, but it did not produce an error when running the code in DynaSim. Specifically, I defined one of my state variables' initial conditions as being of size (Npre, 1) instead of (1, Npre), the latter being the correct convention for DynaSim.

Is DynaSim just smart enough to autocorrect for this, or is there something fishy going on?

Interestingly, I looked in the solve file, and found that it was using the correct definition there - (1, Npre)

To reproduce this effect:

1. Run the following:
```
%% Setup Sparse Pyramidal-Interneuron-Network-Gamma (sPING)

% define equations of cell model (same for E and I populations)
eqns={
  'dv/dt=Iapp+@current; Iapp=0; noise=0'
};
% Tip: monitor all functions of a mechanism using: monitor MECHANISM.functions

% create DynaSim specification structure
s=[];
s.populations(1).name='E';
s.populations(1).size=3;
s.populations(1).equations=eqns;
s.populations(1).mechanism_list={'iNa','iK'};
s.populations(1).parameters={'Iapp',5,'gNa',120,'gK',36};
s.populations(2).name='I';
s.populations(2).size=2;
s.populations(2).equations=eqns;
s.populations(2).mechanism_list={'iNa','iK'};
s.populations(2).parameters={'Iapp',0,'gNa',120,'gK',36};
s.connections(1).direction='I->E';
s.connections(1).mechanism_list={'iGABAa'};
s.connections(1).parameters={'tauD',10,'gGABAa',.1}; % connectivity matrix defined using a string that evalutes to a numeric matrix
s.connections(2).direction='E->I';
s.connections(2).mechanism_list={'iAMPA'};
s.connections(2).parameters={'tauD',2,'gAMPA',.1}; % connectivity set using a numeric matrix defined in script

% Simulate Sparse Pyramidal-Interneuron-Network-Gamma (sPING)
data=dsSimulate(s,'study_dir','deleteme');

dsPlot(data); % <-- Figure 4 in DynaSim paper
```

2. Now, edit iAMPA.mech, and switch the line
``s(0) = IC+IC_noise.*rand(1,N_pre)``
to
``s(0) = IC+IC_noise.*rand(N_pre,1)``

This should be using the _incorrect_ dimensions.

Executing the code in (1) again should not produce any error.

Furthermore, I found that the contents of the solve file were the same in both cases:
``I_E_iAMPA_s(1,:) =  p.I_E_iAMPA_IC+p.I_E_iAMPA_IC_noise.*rand(1,p.E_Npop);``

I feel that this type of mistake should at least produce a warning. Related issue: #154

**Comment by kupiqu** [comment]
I tested this with Npop and it doesn't reverse the order in the solve file, neither Matlab triggers an error because Matlab is smart enough to assign the proper dimension as you can see in the following example:
```
>> y = 1:10;
>> size(y)

ans =

     1    10
>> y(1,:) = (1:10)';
>> size(y)

ans =

     1    10
```

So this is specific to DynaSim setting the positions of Npre and Npost indeces. Will check it out and see if it is easy to trigger a warning.

**Comment by kupiqu** [comment]
Fixed
