### ISSUE TITLE
Should we remove plot2svg functionality from DynaSim?

### ISSUE THREAD

**Issue by kupiqu** [DynaSim/DynaSim#556]
I don't think we need to keep it as part of DynaSim. If for whatever reason we aim to keep it, I will replace plot2svg by fig2svg (https://github.com/kupiqu/fig2svg).

Please let me know what you think it's best.

**Comment by asoplata** [comment]
If `fig2svg` is going to be actively maintained, then I agree it's a good decision. `plot2svg` is definitely abandoned: the last commit was 4 years ago, and the last entry on the changelog was 7 years ago. I do believe there are at least minor changes in the plotting API often enough in Matlab versions; therefore, active maintenance is very helpful. `plot2svg` may be old enough that it's not fully compatible with the big graphics changes in 2014.

So yeah, I think this is a good idea!

**Comment by kupiqu** [comment]
> If fig2svg is going to be actively maintained, then I agree it's a good decision.

I'm the person behind fig2svg, and my current plan is to keep it alive, at least while I continue using Matlab/GNU Octave.

> plot2svg is definitely abandoned: the last commit was 4 years ago, and the last entry on the changelog was 7 years ago

Please note that I have been updating plot2svg functionality, also in DynaSim, for some years now.

> So yeah, I think this is a good idea!

Good, although it's not totally clear to me if the cool idea is to remove it, or to replace it by fig2svg... :)

I personally think that DynaSim and fig2svg are orthogonal, so there is not much of a reason to keep that functionality in DynaSim. If some person wants to use it, that person can easily grab it from https://github.com/kupiqu/fig2svg.

But if you think differently, I may reconsider and keep updating plot2svg functionality in DynaSim...

**Comment by kupiqu** [comment]
Keeping it from now
