### ISSUE TITLE
calc functions return

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#56]
when calc functions are called inside of plot function, they take data and return data with new fields.  these are sometimes nice to have access to. it would be good to have that returned data be part of the output of the plot function.

**Comment by erikthered12** [comment]
eg to get peak frequency out of peak power

**Comment by jsherfey** [comment]
All calc functions used in the plot function can be independently called to get results stored in the desired fields. Analysis results should be obtained using the calc functions (i.e., not the plot functions). If the calc function is called first and the fields are present in data, then dsPlot() uses the values in the field without re-analyzing the data.

**Comment by erik-roberts** [comment]
that's good to know! we should document this under some advanced features. ill put it in the q&a for now.
