### ISSUE TITLE
SimulateModel function error

### ISSUE THREAD

**Issue by The-Tea** [DynaSim/DynaSim#564]
Hello,
I cloned DynaSim into my MATLAB as proposed and then tried to run one of the script M-files from PFC_models directory. I got the error regarding the SimulateModel function. Apparently, the function was non existent. 

I could not find any other solutions besides changing all the "SimulateModel" functions with "dsSimulate". This worked, but my question is - why would there be SimulateModel function in the script if there is no proper function M-file for it? Or am I missing something?

Thank you in advance!
Tea

**Comment by jsherfey** [comment]
Hi Tea,

Thank you for catching this. The script should call dsSimulate, not
SimulateModel. If you see PlotData being called anywhere, that should be
replaced by dsPlot. I will update the scripts this week to call the proper
functions. Please let me know if you have any other trouble.

Thanks,
Jason

**Comment by The-Tea** [comment]
Dear Jason,
thanks for the reply. Indeed, I had the same issue with PlotData, so I resolved it the same way. Besides that, DynaSim works nice for me!

All the best,
Tea

**Comment by kupiqu** [comment]
I assume this is fixed
