### ISSUE TITLE
question regarding sPING setup

### ISSUE THREAD

**Issue by The-Tea** [DynaSim/DynaSim#568]
Hi,
I am currently exploring different DynaSim possibilities. In the Getting Started tutorial, there is a code corresponding to sPING simulation.

My question is: 
What is the purpose of `randn(1,N_pop)` in `eqns={'dv/dt=Iapp+@current+noise*randn(1,N_pop); Iapp=0; noise=0'}`?

Thanks in advance,
Tea

**Comment by jsherfey** [comment]
Without the noise, all E cells spike on every cycle. The noise enables
different subsets to engage feedback inhibition from cycle to cycle (i.e.,
it produces a "weak" or "sparse" PING).
