### ISSUE TITLE
code visualization

### ISSUE THREAD

**Issue by erikthered12** [DynaSim/DynaSim#57]
have a visualization of how the functions call each other like: [https://github.com/fzaninotto/CodeFlower](https://github.com/fzaninotto/CodeFlower)

or
[https://github.com/fzaninotto/DependencyWheel](https://github.com/fzaninotto/DependencyWheel)

**Comment by kupiqu** [comment]
Somehow related to that, I used mDepsGraphviz on Dynasim about 9 months ago with the following results (you can set a recursion order, shown for 1st order)

![simulatemodel-nq8](https://cloud.githubusercontent.com/assets/3875196/22157034/ef200796-df03-11e6-809f-6ee928229333.png)

**Comment by erikthered12** [comment]
![screen shot 2017-01-20 at 3 38 16 pm](https://cloud.githubusercontent.com/assets/4479319/22164754/843da56e-df26-11e6-9fba-5b702a5d32e7.jpg)

**Comment by erikthered12** [comment]
salva, can you share that code please? that's so cool!

**Comment by erikthered12** [comment]
the functions have changed from that old one.

**Comment by kupiqu** [comment]
Sure, I can run the code again on the current version of DynaSim...

We will need to see whether we can simply add the code or not, as my version derives from (actually basically is) a matlab file exchange toolbox.

**Comment by kupiqu** [comment]
Current version

![nu_simulatemodel-nq8](https://cloud.githubusercontent.com/assets/3875196/22271614/6d1fa478-e263-11e6-94ec-a4637f34bec6.png)

**Comment by erikthered12** [comment]
Thanks!! and that is why i was so confused debugging haha. wow!

check it out @asoplata

**Comment by asoplata** [comment]
dat CheckOptions tho

Why are some of the connections red? What does that mean?

**Comment by asoplata** [comment]
This is now accomplished by the documentation generation system from https://github.com/DynaSim/DynaSim/issues/18 assuming you have GraphViz installed on your system, and if you build the documentation.
