### ISSUE TITLE
Error running dsSimulate in MATLAB 2019b

### ISSUE THREAD

**Issue by MunibH** [DynaSim/DynaSim#576]
I receive the following error when I attempt to run the dsTutorial provided in the demos directory. it looks like [this prior issue](https://github.com/DynaSim/DynaSim/issues/557) might be related as well

Error:File: dsSimulate.m Line: 812 Column: 64
Identifier 'sim_id' is not a function or a shared variable. To share 'sim_id' with nested function,
initialize it in the current scope. For more information, see Sharing Variables Between Parent and Nested
Functions.

Error in dsTutorial (line 50)
data=dsSimulate(eqns,'tspan',[0 100],'ic',[1 2 .5],'solver','rk4');

**Comment by kupiqu** [comment]
fixed by pull request #578
