### ISSUE TITLE
xPlt Multi-dimensional plotting framework

### ISSUE THREAD

**Issue by davestanley** [DynaSim/DynaSim#59]
This issue is for implementing the plotting framework developed during last DynaSim meeting. (See Google Docs)
![img_2303](https://cloud.githubusercontent.com/assets/5439305/22176983/9529cdfe-dfe3-11e6-802b-556f77c85275.jpeg)

![img_2304](https://cloud.githubusercontent.com/assets/5439305/22176985/9995fc0a-dfe3-11e6-8369-16dd06e33518.jpeg)

**Comment by davestanley** [comment]
Just merged preliminary version of this code.

**Comment by erikthered12** [comment]
i feel like we should move this to dependencies, since it's independent of dynasim and going to be its own thing, so its more like an external dependency than internal function.  that way, @davestanley , you can keep updating it for non-dynasim stuff and just add the latest version in dynasim and your own repo.

**Comment by erikthered12** [comment]
@davestanley one issue I think exists is the situation when the data is not a perfect meshgrid, and perhaps when the data is not ordered.  With dynamism's covary feature, the data points often won't be a full hypercube, let alone even spaced, or in monotonically increasing order.

**Comment by davestanley** [comment]
@erikthered12 
It should be okay fine if the data is sparse (e.g. not meshgrid). 

There is an example using sparse data in the demos, but it might need to be updated, which I'll do tomorrow.

**Comment by erikthered12** [comment]
ok cool!

**Comment by davestanley** [comment]
Just spent most of today day working on updates to the demo script. There are some substantial changes - namely, added a bunch of support for regular expressions. Also, you now need to submit a 0 or "data" to recursivePlot as the final entry in the dimensions argument. This denotes referencing xp.data.

**Comment by erikthered12** [comment]
PyPet is a python toolkit that has overlap with what we're trying to do.
https://pypet.readthedocs.io/en/latest/

**Comment by davestanley** [comment]
Interesting. Seems like PyPet is a bit more like "github for modeling" rather than data analysis and visualization. Is this the sense you got as well?

I guess the overlap would be that both involve storing data and the associated parameters.
The difference would be that ours allows more manipulation of those parameters, whereas theirs focuses on I/O and data storage.

Still, I much like the idea of stitching multiple simulation runs together and storing them in one huge archive. Perhaps I will tweak xPlt to do this also, and add it to the demos file. The modifications should be fairly minor.

Thanks for sharing!

**Comment by erikthered12** [comment]
https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

**Comment by erikthered12** [comment]
https://github.com/blog/2104-working-with…

**Comment by davestanley** [comment]
I like that we are officially using "Advanced Git"  @erikthered12 

![image](https://cloud.githubusercontent.com/assets/5439305/23826800/b2ce964a-0672-11e7-8eac-1f66d74ab64d.png)

**Comment by erik-roberts** [comment]
closed this to switch to md
