### ISSUE TITLE
how does one change parameter mid way through simulation?

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#62]
eg if one wishes to change leak conductance or some state variable at a certain time point or during a certain interval

**Comment by erik-roberts** [comment]
perhaps add a capability for the parameter to be specified as a vector that gets indexed at each time point? it wouldn't work with built-in solvers

**Comment by jsherfey** [comment]
The way to achieve this is to define the parameter as a function of time.

Example: (leak current turns on at t=50ms)
eqns='dV/dt=10+@current+gl(t)*(V+65); {iNa,iK}; gl(t)=0*(t<50)+.8*(t>50)';
dsPlot(dsSimulate(eqns));

**Comment by erik-roberts** [comment]
added to wiki q&a
