### ISSUE TITLE
[BUG] All terms added to linkers after a state variable are ignored

### ISSUE THREAD

**Issue by sardid** [DynaSim/DynaSim#641]
**Describe the bug**

Consider a linker such as @current composed of several terms. The issue is that all terms that come after one that is a state variable (usually they are functions) are ignored. These terms are sorted according to the intrinsic mechanism list first, then connections.

**pseudo-code**

```
@current += function1(t)
@current += state_variable1
@current += function2(V)
@current += state_variable2
...
```

In this case, `@current` is replaced by `function1(t) + state_variable1` independently of the sorting afterwards (between function2 and state_variable2).

**Expected behavior**

No terms should be excluded from the linker

**Additional context**

This is a dangerous issue because no error is triggered and the simulation is executed as if those terms didn't exist, without the user realizing of the problem

**Workaround**

One can define extra functions like this `f(t) = state_variable` and add them to the linker, for instance: `@current += f(t)` to avoid the issue until it's fixed. Unfortunately, this is far from optimal as users are not in general aware of the issue and the workaround

**Comment by kupiqu** [comment]
@jsherfey, I accepted a pull request that fixes this issue in the dev branch. The issue was in `linker_strrep`, inside the conditional for single variables (such as state variables), which missed adding the linker for potential extra terms.

Please review and if everything seems fine, please merge into master.
