### ISSUE TITLE
Create a live script tutorial for the Unbiased Competition model

### ISSUE THREAD

**Issue by kupiqu** [DynaSim/DynaSim#657]
Implement the Unbiased Competition model (Ardid et al., PNAS 2019) as a DynaSim live script tutorial with two main aims. First, to illustrate the creation and usage of DynaSim models endowed with mechanisms specified by the user. And second, to show how to modify the dynamics of a model, the Unbiased Competition model in this case, by tuning its internal parameters.

This issue is related to issue #633

**Comment by jsherfey** [comment]
This issue was resolved in Pull Request #658
