### ISSUE TITLE
SGE qsub array mode

### ISSUE THREAD

**Issue by erikthered12** [DynaSim/DynaSim#81]
It seems like a bottle neck in batch submission for short sims is the time it takes to submit the jobs, especially from the login node when it's slow.  The "qsub -t” array notation can do the qsub with 1 line instead of having to use a loop.

**Comment by erikthered12** [comment]
i renamed qmatjob to qmatjob_loop and added qmatjob_array. qmatjobs_memlimit is renamed to qmatjobs_memlimit_loop. qmatjobs_memlimit_array was a temp solution that currently isn't used. if one selected option 'qsub_mode'='array' instead of the default 'loop', CreateBash will directly call qsub with qmatjob_array.

thus, array mode avoids a for loop.  one issue is that the qsub command can hang, although I'm not sure if this is different than if a qmatjobs_memlimit hangs.

**Comment by erikthered12** [comment]
something i'm still figuring out and could use advice on is how to specify output and error path when using the -t flag with qsub.  i tried adding an sge directive to qmatjob_array with #$ notation but didn't seem to work.  i read somewhere that the directives don't have access to the shell variables but i'm uncertain.

**Comment by erikthered12** [comment]
i also switched to 2014b from 2014a for cluster, but only for new array mode.  the default old mode is the same as before functionally.

**Comment by benpolletta** [comment]
Can this issue be closed?
