### ISSUE TITLE
Remove all anonymous functions

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#87]
Anonymous function calls are really really slow in matlab.  We should remove all of them if possible.

**Comment by jsherfey** [comment]
This is possible using dsPropagateFunctions() and is the default behavior of dsWriteDynaSimSolver().

**Comment by erik-roberts** [comment]
I didn't just mean in the solve file. I meant in the actual code. They are found in cell fun's all over the place.

**Comment by jsherfey** [comment]
They are needed in the code to properly evaluate functions that depend on
them.

**Comment by erik-roberts** [comment]
> They are needed in the code to properly evaluate functions that depend on them.

I can't think programmatically why a matlab (specifically) anonymous function is ever needed or superior over a nested function at the least, or alternatively a local or external function. Do you have an example? The speed enhancements are maybe not worth it, but it may be worth checking the profile to see how much the anonymous functions slow the code down.

E.g., even matlab uses poor practices with making anonymous functions the standard for callbacks: https://undocumentedmatlab.com/blog/callback-functions-performance
