### ISSUE TITLE
mode for one simulation file of each type

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#90]
i tried to submit 18000 simulations.  It took 8 hours to make 13000 of the sim job m files. is there a way to share a single m file among different jobs when its the same file?  perhaps compile mode does this?

**Comment by erikthered12** [comment]
strategy:

have ds make a linker file that accepts a simID and will spit out the proper m/mex file to run.
ex simjobDispatcher(simID) -> correct_m_file and parameter index.

make a single parameter file with matrices containing parameters for all sims. have simjobDispatcher give correct index to correct_m_file

**Comment by erikthered12** [comment]
problem: concurrent loading of mat files

solution: write all parameters to 1 csv file or similar.

**Comment by erik-roberts** [comment]
first try mat file again though

**Comment by erik-roberts** [comment]
status: pretty much finished with CreateBatch.

**Comment by erik-roberts** [comment]
finished coding. now testing.

issue with line 34 of checkhostpaths called from sim_job line 8

**Comment by erik-roberts** [comment]
todo: compile job_file.
* remove try and catch, rmfield
* declare fullfile as coder.extrinsic
* load should probably be assigned to a struct.

**Comment by erik-roberts** [comment]
added to dev branch

**Comment by erik-roberts** [comment]
TODO: add one file mode for parallel

**Comment by erik-roberts** [comment]
branch iss90_one_file_mode_for_parallel

**Comment by jsherfey** [comment]
Has this been achieved with the 'array' option for  'qsub_mode' in dsCreateBatch()?

**Comment by erik-roberts** [comment]
> Has this been achieved with the 'array' option for 'qsub_mode' in dsCreateBatch()?

no, this is more regarding `one_solve_file_flag`, but havent tested this in awhile.

**Comment by erik-roberts** [comment]
`one_solve_file_flag` still doesn't work with `sims_per_job` > 1. not sure about `parfor_flag`

**Comment by erik-roberts** [comment]
onefile mode allows non-unique parameters (ie multiple namespace matches) now.  allows non-numeric data types in vary if not mex. when mex, varys must be numeric.

**Comment by erik-roberts** [comment]
sims_per_job >1 works

**Comment by erik-roberts** [comment]
added wiki page
https://github.com/DynaSim/DynaSim/wiki/One-Solve-File-Flag-Mode

**Comment by erik-roberts** [comment]
for parfor mode, some of the sims ran, some didn't, there's this error:
`a profile with name 'local_#####' already exists`

**Comment by erik-roberts** [comment]
this will be continued in #344
