### ISSUE TITLE
findDemosPath

### ISSUE THREAD

**Issue by davestanley** [DynaSim/DynaSim#94]
This function needs to be in the path in order to work. However, the following chunk of code requires it in order to set up the path in the first place

> % Get ready...
>
>demos_path = findDemosPath;
>
>% Set path to your copy of the DynaSim toolbox
>dynasim_path = fullfile(demos_path, '..');
>
>% add DynaSim toolbox to Matlab path
>addpath(genpath(dynasim_path)); % comment this out if already in path

(e.g. try running it after running restoredefaultpath)

Assigning @erikthered12 , since I think he wrote this

**Comment by erikthered12** [comment]
duplicated in #97
fixed: 3c8eb7e
