### ISSUE TITLE
Submodules for dependencies

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#95]
problem: i have a separate repo that is actively being developed for multi-dimension plotting. i want dynasim to pull from the repo.

solution: git submodules

caveat: more complicated, but no additional effort with a shell script and an alias to that shell script.

I'd like to propose using dependencies for Dave and my multi-dim plotting code since they work outside dynasim.  there is a little more work involved, but i think we could write a bash and windows shell script that would make it easy to do.

https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by erikthered12** [comment]
i implemented this for my gimbl-vis.  let me know if there are any issues.
