### ISSUE TITLE
Post simulation analysis

### ISSUE THREAD

**Issue by erik-roberts** [DynaSim/DynaSim#98]
AnalyzeData After Sim gets same indexed ResultFile name as if run during simulation

**Comment by erikthered12** [comment]
need to rewrite analyzeData to auto generate resultFilenames when feeding in a data array

**Comment by erikthered12** [comment]
was accidentally duplicated in #111

**Comment by benpolletta** [comment]
ae34c79f1ab2d27518cb06f8470ebc0ed9ea4785
